//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionCostos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionCostos.CostosSoap")]
    public interface CostosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_costo_prod_linea_neg_resu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_costo_prod_linea_neg_resu(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_costo_prod_linea_neg_resu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_costo_prod_linea_neg_resuAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_costo_prod_linea_neg_det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_costo_prod_linea_neg_det(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_costo_prod_linea_neg_det", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_costo_prod_linea_neg_detAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ManoObra_ImprodNatuG_Det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_ManoObra_ImprodNatuG_Det(string V_Centro_Operativo, string D_Año_de_Proceso, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ManoObra_ImprodNatuG_Det", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_ManoObra_ImprodNatuG_DetAsync(string V_Centro_Operativo, string D_Año_de_Proceso, string D_Mes, string UserName);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Listar_Costo_Prod_Linea_Neg_Det) del mensaje Listar_Costo_Prod_Linea_Neg_DetRequest no coincide con el valor predeterminado (Listar_Costo_Prod_Linea_Neg_Det1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Costo_Prod_Linea_Neg_Det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetResponse Listar_Costo_Prod_Linea_Neg_Det1(SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Costo_Prod_Linea_Neg_Det", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetResponse> Listar_Costo_Prod_Linea_Neg_Det1Async(SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Costo_VentasLineaNegocioRes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Costo_VentasLineaNegocioRes(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Linea_Negocio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Costo_VentasLineaNegocioRes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Costo_VentasLineaNegocioResAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Linea_Negocio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_CostPro_por_Linea_Neg_R", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_CostPro_por_Linea_Neg_R(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_CostPro_por_Linea_Neg_R", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_CostPro_por_Linea_Neg_RAsync(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_CostPro_por_Linea_Neg_D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_CostPro_por_Linea_Neg_D(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_CostPro_por_Linea_Neg_D", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_CostPro_por_Linea_Neg_DAsync(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Hors_HombreNormalUtili_Divi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Hors_HombreNormalUtili_Divi(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Hors_HombreNormalUtili_Divi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Hors_HombreNormalUtili_DiviAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Distri_Costo_Grup_Resu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Distri_Costo_Grup_Resu(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Distri_Costo_Grup_Resu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Distri_Costo_Grup_ResuAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Distri_Costo_Grup_CC_Det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Distri_Costo_Grup_CC_Det(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Grupo_CC_Desde, string V_Grupo_CC_Hasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Distri_Costo_Grup_CC_Det", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Distri_Costo_Grup_CC_DetAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Grupo_CC_Desde, string V_Grupo_CC_Hasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Mano_Obra_Directa_Div_Det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Mano_Obra_Directa_Div_Det(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Division_Inicial, string V_Division_Final, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Mano_Obra_Directa_Div_Det", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Mano_Obra_Directa_Div_DetAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Division_Inicial, string V_Division_Final, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_CostosDirectos_OT_CC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_CostosDirectos_OT_CC(string V_Centro_Operativo, string v_Anio, string v_Mes, string V_Linea_Neg, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_CostosDirectos_OT_CC", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_CostosDirectos_OT_CCAsync(string V_Centro_Operativo, string v_Anio, string v_Mes, string V_Linea_Neg, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Materiales_en_Proyectos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_Materiales_en_Proyectos(string V_Centro_Operativo, string v_materiales, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Materiales_en_Proyectos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_Materiales_en_ProyectosAsync(string V_Centro_Operativo, string v_materiales, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_analisis_gastos_ccnatudet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_analisis_gastos_ccnatudet(string D_AÑO_DE_PROCESO, string D_MES_DE_PROCESO, string V_CENTRO_OPERATIVO, string V_CUENTA_MAYOR, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_analisis_gastos_ccnatudet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_analisis_gastos_ccnatudetAsync(string D_AÑO_DE_PROCESO, string D_MES_DE_PROCESO, string V_CENTRO_OPERATIVO, string V_CUENTA_MAYOR, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_analisis_gast_itemsasient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_analisis_gast_itemsasient(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_analisis_gast_itemsasient", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_analisis_gast_itemsasientAsync(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Ventas_diferidas_x_OT_detalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Ventas_diferidas_x_OT_detalle(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Ventas_diferidas_x_OT_detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Ventas_diferidas_x_OT_detalleAsync(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Ventas_diferidas_x_Doc_detalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Ventas_diferidas_x_Doc_detalle(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Ventas_diferidas_x_Doc_detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Ventas_diferidas_x_Doc_detalleAsync(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar_Costo_Prod_Linea_Neg_Det", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Listar_Costo_Prod_Linea_Neg_DetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string D_Año;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string D_Mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string V_Centro_Operativo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string V_Linea_Negocio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string UserName;
        
        public Listar_Costo_Prod_Linea_Neg_DetRequest() {
        }
        
        public Listar_Costo_Prod_Linea_Neg_DetRequest(string D_Año, string D_Mes, string V_Centro_Operativo, string V_Linea_Negocio, string UserName) {
            this.D_Año = D_Año;
            this.D_Mes = D_Mes;
            this.V_Centro_Operativo = V_Centro_Operativo;
            this.V_Linea_Negocio = V_Linea_Negocio;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar_Costo_Prod_Linea_Neg_DetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Listar_Costo_Prod_Linea_Neg_DetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable Listar_Costo_Prod_Linea_Neg_DetResult;
        
        public Listar_Costo_Prod_Linea_Neg_DetResponse() {
        }
        
        public Listar_Costo_Prod_Linea_Neg_DetResponse(System.Data.DataTable Listar_Costo_Prod_Linea_Neg_DetResult) {
            this.Listar_Costo_Prod_Linea_Neg_DetResult = Listar_Costo_Prod_Linea_Neg_DetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CostosSoapChannel : SIMANET_W22R.srvGestionCostos.CostosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CostosSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionCostos.CostosSoap>, SIMANET_W22R.srvGestionCostos.CostosSoap {
        
        public CostosSoapClient() {
        }
        
        public CostosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CostosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CostosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CostosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Listar_costo_prod_linea_neg_resu(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName) {
            return base.Channel.Listar_costo_prod_linea_neg_resu(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_LINEA_NEGOCIO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_costo_prod_linea_neg_resuAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName) {
            return base.Channel.Listar_costo_prod_linea_neg_resuAsync(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_LINEA_NEGOCIO, UserName);
        }
        
        public System.Data.DataTable Listar_costo_prod_linea_neg_det(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName) {
            return base.Channel.Listar_costo_prod_linea_neg_det(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_LINEA_NEGOCIO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_costo_prod_linea_neg_detAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_LINEA_NEGOCIO, string UserName) {
            return base.Channel.Listar_costo_prod_linea_neg_detAsync(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_LINEA_NEGOCIO, UserName);
        }
        
        public System.Data.DataTable Listar_ManoObra_ImprodNatuG_Det(string V_Centro_Operativo, string D_Año_de_Proceso, string D_Mes, string UserName) {
            return base.Channel.Listar_ManoObra_ImprodNatuG_Det(V_Centro_Operativo, D_Año_de_Proceso, D_Mes, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_ManoObra_ImprodNatuG_DetAsync(string V_Centro_Operativo, string D_Año_de_Proceso, string D_Mes, string UserName) {
            return base.Channel.Listar_ManoObra_ImprodNatuG_DetAsync(V_Centro_Operativo, D_Año_de_Proceso, D_Mes, UserName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetResponse SIMANET_W22R.srvGestionCostos.CostosSoap.Listar_Costo_Prod_Linea_Neg_Det1(SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest request) {
            return base.Channel.Listar_Costo_Prod_Linea_Neg_Det1(request);
        }
        
        public System.Data.DataTable Listar_Costo_Prod_Linea_Neg_Det1(string D_Año, string D_Mes, string V_Centro_Operativo, string V_Linea_Negocio, string UserName) {
            SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest inValue = new SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest();
            inValue.D_Año = D_Año;
            inValue.D_Mes = D_Mes;
            inValue.V_Centro_Operativo = V_Centro_Operativo;
            inValue.V_Linea_Negocio = V_Linea_Negocio;
            inValue.UserName = UserName;
            SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetResponse retVal = ((SIMANET_W22R.srvGestionCostos.CostosSoap)(this)).Listar_Costo_Prod_Linea_Neg_Det1(inValue);
            return retVal.Listar_Costo_Prod_Linea_Neg_DetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetResponse> SIMANET_W22R.srvGestionCostos.CostosSoap.Listar_Costo_Prod_Linea_Neg_Det1Async(SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest request) {
            return base.Channel.Listar_Costo_Prod_Linea_Neg_Det1Async(request);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetResponse> Listar_Costo_Prod_Linea_Neg_Det1Async(string D_Año, string D_Mes, string V_Centro_Operativo, string V_Linea_Negocio, string UserName) {
            SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest inValue = new SIMANET_W22R.srvGestionCostos.Listar_Costo_Prod_Linea_Neg_DetRequest();
            inValue.D_Año = D_Año;
            inValue.D_Mes = D_Mes;
            inValue.V_Centro_Operativo = V_Centro_Operativo;
            inValue.V_Linea_Negocio = V_Linea_Negocio;
            inValue.UserName = UserName;
            return ((SIMANET_W22R.srvGestionCostos.CostosSoap)(this)).Listar_Costo_Prod_Linea_Neg_Det1Async(inValue);
        }
        
        public System.Data.DataTable Listar_Costo_VentasLineaNegocioRes(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Linea_Negocio, string UserName) {
            return base.Channel.Listar_Costo_VentasLineaNegocioRes(V_Centro_Operativo, D_Año, D_Mes, V_Linea_Negocio, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Costo_VentasLineaNegocioResAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Linea_Negocio, string UserName) {
            return base.Channel.Listar_Costo_VentasLineaNegocioResAsync(V_Centro_Operativo, D_Año, D_Mes, V_Linea_Negocio, UserName);
        }
        
        public System.Data.DataTable Listar_CostPro_por_Linea_Neg_R(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName) {
            return base.Channel.Listar_CostPro_por_Linea_Neg_R(Centro_Operativo, Periodo, Linea_Negocio, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_CostPro_por_Linea_Neg_RAsync(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName) {
            return base.Channel.Listar_CostPro_por_Linea_Neg_RAsync(Centro_Operativo, Periodo, Linea_Negocio, UserName);
        }
        
        public System.Data.DataTable Listar_CostPro_por_Linea_Neg_D(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName) {
            return base.Channel.Listar_CostPro_por_Linea_Neg_D(Centro_Operativo, Periodo, Linea_Negocio, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_CostPro_por_Linea_Neg_DAsync(string Centro_Operativo, string Periodo, string Linea_Negocio, string UserName) {
            return base.Channel.Listar_CostPro_por_Linea_Neg_DAsync(Centro_Operativo, Periodo, Linea_Negocio, UserName);
        }
        
        public System.Data.DataTable Listar_Hors_HombreNormalUtili_Divi(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Hors_HombreNormalUtili_Divi(V_Centro_Operativo, D_Año, D_Mes, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Hors_HombreNormalUtili_DiviAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Hors_HombreNormalUtili_DiviAsync(V_Centro_Operativo, D_Año, D_Mes, UserName);
        }
        
        public System.Data.DataTable Listar_Distri_Costo_Grup_Resu(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Distri_Costo_Grup_Resu(V_Centro_Operativo, D_Año, D_Mes, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Distri_Costo_Grup_ResuAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Distri_Costo_Grup_ResuAsync(V_Centro_Operativo, D_Año, D_Mes, UserName);
        }
        
        public System.Data.DataTable Listar_Distri_Costo_Grup_CC_Det(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Grupo_CC_Desde, string V_Grupo_CC_Hasta, string UserName) {
            return base.Channel.Listar_Distri_Costo_Grup_CC_Det(V_Centro_Operativo, D_Año, D_Mes, V_Grupo_CC_Desde, V_Grupo_CC_Hasta, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Distri_Costo_Grup_CC_DetAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Grupo_CC_Desde, string V_Grupo_CC_Hasta, string UserName) {
            return base.Channel.Listar_Distri_Costo_Grup_CC_DetAsync(V_Centro_Operativo, D_Año, D_Mes, V_Grupo_CC_Desde, V_Grupo_CC_Hasta, UserName);
        }
        
        public System.Data.DataTable Listar_Mano_Obra_Directa_Div_Det(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Division_Inicial, string V_Division_Final, string UserName) {
            return base.Channel.Listar_Mano_Obra_Directa_Div_Det(V_Centro_Operativo, D_Año, D_Mes, V_Division_Inicial, V_Division_Final, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Mano_Obra_Directa_Div_DetAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string V_Division_Inicial, string V_Division_Final, string UserName) {
            return base.Channel.Listar_Mano_Obra_Directa_Div_DetAsync(V_Centro_Operativo, D_Año, D_Mes, V_Division_Inicial, V_Division_Final, UserName);
        }
        
        public string Listar_CostosDirectos_OT_CC(string V_Centro_Operativo, string v_Anio, string v_Mes, string V_Linea_Neg, string UserName) {
            return base.Channel.Listar_CostosDirectos_OT_CC(V_Centro_Operativo, v_Anio, v_Mes, V_Linea_Neg, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_CostosDirectos_OT_CCAsync(string V_Centro_Operativo, string v_Anio, string v_Mes, string V_Linea_Neg, string UserName) {
            return base.Channel.Listar_CostosDirectos_OT_CCAsync(V_Centro_Operativo, v_Anio, v_Mes, V_Linea_Neg, UserName);
        }
        
        public string Listar_Materiales_en_Proyectos(string V_Centro_Operativo, string v_materiales, string UserName) {
            return base.Channel.Listar_Materiales_en_Proyectos(V_Centro_Operativo, v_materiales, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_Materiales_en_ProyectosAsync(string V_Centro_Operativo, string v_materiales, string UserName) {
            return base.Channel.Listar_Materiales_en_ProyectosAsync(V_Centro_Operativo, v_materiales, UserName);
        }
        
        public System.Data.DataTable Listar_analisis_gastos_ccnatudet(string D_AÑO_DE_PROCESO, string D_MES_DE_PROCESO, string V_CENTRO_OPERATIVO, string V_CUENTA_MAYOR, string UserName) {
            return base.Channel.Listar_analisis_gastos_ccnatudet(D_AÑO_DE_PROCESO, D_MES_DE_PROCESO, V_CENTRO_OPERATIVO, V_CUENTA_MAYOR, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_analisis_gastos_ccnatudetAsync(string D_AÑO_DE_PROCESO, string D_MES_DE_PROCESO, string V_CENTRO_OPERATIVO, string V_CUENTA_MAYOR, string UserName) {
            return base.Channel.Listar_analisis_gastos_ccnatudetAsync(D_AÑO_DE_PROCESO, D_MES_DE_PROCESO, V_CENTRO_OPERATIVO, V_CUENTA_MAYOR, UserName);
        }
        
        public System.Data.DataTable Listar_analisis_gast_itemsasient(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName) {
            return base.Channel.Listar_analisis_gast_itemsasient(V_CENTRO_OPERATIVO, V_DIVISION, V_NUMERO_OT, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_analisis_gast_itemsasientAsync(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName) {
            return base.Channel.Listar_analisis_gast_itemsasientAsync(V_CENTRO_OPERATIVO, V_DIVISION, V_NUMERO_OT, UserName);
        }
        
        public System.Data.DataTable Listar_Ventas_diferidas_x_OT_detalle(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName) {
            return base.Channel.Listar_Ventas_diferidas_x_OT_detalle(V_PERIODO, V_CENTRO_OPERATIVO, V_DIVISION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Ventas_diferidas_x_OT_detalleAsync(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName) {
            return base.Channel.Listar_Ventas_diferidas_x_OT_detalleAsync(V_PERIODO, V_CENTRO_OPERATIVO, V_DIVISION, UserName);
        }
        
        public System.Data.DataTable Listar_Ventas_diferidas_x_Doc_detalle(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName) {
            return base.Channel.Listar_Ventas_diferidas_x_Doc_detalle(V_PERIODO, V_CENTRO_OPERATIVO, V_DIVISION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Ventas_diferidas_x_Doc_detalleAsync(string V_PERIODO, string V_CENTRO_OPERATIVO, string V_DIVISION, string UserName) {
            return base.Channel.Listar_Ventas_diferidas_x_Doc_detalleAsync(V_PERIODO, V_CENTRO_OPERATIVO, V_DIVISION, UserName);
        }
    }
}
