//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvProyectos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvProyectos.ProyectosSoap")]
    public interface ProyectosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProyectosSIMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarProyectosSIMA(string IdProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProyectosSIMA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarProyectosSIMAAsync(string IdProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleProyectosSIMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        SIMANET_W22R.srvProyectos.ProyectoBE DetalleProyectosSIMA(string IdProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleProyectosSIMA", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvProyectos.ProyectoBE> DetalleProyectosSIMAAsync(string IdProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPryectoPor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable BuscarPryectoPor(int TipoBusqueda, string Citerio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPryectoPor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarPryectoPorAsync(int TipoBusqueda, string Citerio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaModificaProyecto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int InsertaModificaProyecto(SIMANET_W22R.srvProyectos.ProyectoBE oProyectoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaModificaProyecto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertaModificaProyectoAsync(SIMANET_W22R.srvProyectos.ProyectoBE oProyectoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProyectoInsAct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int ProyectoInsAct(int IdProyecto, string Codigo, string Nombre, string Descripcion, int IdCliente, int IdLN, int IdEstado, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProyectoInsAct", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ProyectoInsActAsync(int IdProyecto, string Codigo, string Nombre, string Descripcion, int IdCliente, int IdLN, int IdEstado, int IdUsuario, string UserName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProyectoBE : BaseBE {
        
        private int idProyectoField;
        
        private string codigoProyField;
        
        private string nombreField;
        
        private int idClienteField;
        
        private string clienteRazonSocialField;
        
        private int idLNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdProyecto {
            get {
                return this.idProyectoField;
            }
            set {
                this.idProyectoField = value;
                this.RaisePropertyChanged("IdProyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoProy {
            get {
                return this.codigoProyField;
            }
            set {
                this.codigoProyField = value;
                this.RaisePropertyChanged("CodigoProy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("IdCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClienteRazonSocial {
            get {
                return this.clienteRazonSocialField;
            }
            set {
                this.clienteRazonSocialField = value;
                this.RaisePropertyChanged("ClienteRazonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int IdLN {
            get {
                return this.idLNField;
            }
            set {
                this.idLNField = value;
                this.RaisePropertyChanged("IdLN");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProyectoBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string sucursalField;
        
        private string estacionField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        private System.DateTime fechaField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado {
            get {
                return this.imgEstadoField;
            }
            set {
                this.imgEstadoField = value;
                this.RaisePropertyChanged("ImgEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado {
            get {
                return this.nombreEstadoField;
            }
            set {
                this.nombreEstadoField = value;
                this.RaisePropertyChanged("NombreEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
                this.RaisePropertyChanged("Estacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdCodigo {
            get {
                return this.idCodigoField;
            }
            set {
                this.idCodigoField = value;
                this.RaisePropertyChanged("IdCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
                this.RaisePropertyChanged("ambiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProyectosSoapChannel : SIMANET_W22R.srvProyectos.ProyectosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProyectosSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvProyectos.ProyectosSoap>, SIMANET_W22R.srvProyectos.ProyectosSoap {
        
        public ProyectosSoapClient() {
        }
        
        public ProyectosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProyectosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProyectosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarProyectosSIMA(string IdProyecto, string UserName) {
            return base.Channel.ListarProyectosSIMA(IdProyecto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarProyectosSIMAAsync(string IdProyecto, string UserName) {
            return base.Channel.ListarProyectosSIMAAsync(IdProyecto, UserName);
        }
        
        public SIMANET_W22R.srvProyectos.ProyectoBE DetalleProyectosSIMA(string IdProyecto, string UserName) {
            return base.Channel.DetalleProyectosSIMA(IdProyecto, UserName);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvProyectos.ProyectoBE> DetalleProyectosSIMAAsync(string IdProyecto, string UserName) {
            return base.Channel.DetalleProyectosSIMAAsync(IdProyecto, UserName);
        }
        
        public System.Data.DataTable BuscarPryectoPor(int TipoBusqueda, string Citerio, string UserName) {
            return base.Channel.BuscarPryectoPor(TipoBusqueda, Citerio, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarPryectoPorAsync(int TipoBusqueda, string Citerio, string UserName) {
            return base.Channel.BuscarPryectoPorAsync(TipoBusqueda, Citerio, UserName);
        }
        
        public int InsertaModificaProyecto(SIMANET_W22R.srvProyectos.ProyectoBE oProyectoBE) {
            return base.Channel.InsertaModificaProyecto(oProyectoBE);
        }
        
        public System.Threading.Tasks.Task<int> InsertaModificaProyectoAsync(SIMANET_W22R.srvProyectos.ProyectoBE oProyectoBE) {
            return base.Channel.InsertaModificaProyectoAsync(oProyectoBE);
        }
        
        public int ProyectoInsAct(int IdProyecto, string Codigo, string Nombre, string Descripcion, int IdCliente, int IdLN, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.ProyectoInsAct(IdProyecto, Codigo, Nombre, Descripcion, IdCliente, IdLN, IdEstado, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<int> ProyectoInsActAsync(int IdProyecto, string Codigo, string Nombre, string Descripcion, int IdCliente, int IdLN, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.ProyectoInsActAsync(IdProyecto, Codigo, Nombre, Descripcion, IdCliente, IdLN, IdEstado, IdUsuario, UserName);
        }
    }
}
