//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvSeguridad {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CoreSIMAdll.org/", ConfigurationName="srvSeguridad.SeguridadSoap")]
    public interface SeguridadSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetPerfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPerfiles(int IdUser, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetPerfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPerfilesAsync(int IdUser, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/ValidateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ValidateUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ValidateUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/ValidateUserAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ValidateUserAD(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/ValidateUserAD", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ValidateUserADAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/VerificaCaducidadUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool VerificaCaducidadUser(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/VerificaCaducidadUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> VerificaCaducidadUserAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetOptionsByProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOptionsByProfile(int idSystem, int idProfile, string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetOptionsByProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOptionsByProfileAsync(int idSystem, int idProfile, string pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetPerfilAccesoDirecto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPerfilAccesoDirecto(int idSystem, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetPerfilAccesoDirecto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPerfilAccesoDirectoAsync(int idSystem, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetDatosUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        SIMANET_W22R.srvSeguridad.UsuarioBE GetDatosUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/GetDatosUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvSeguridad.UsuarioBE> GetDatosUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/CodigoUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable CodigoUsuario(string s_idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/CodigoUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> CodigoUsuarioAsync(string s_idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/AsignarSucursal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int AsignarSucursal(int i_IdUsuario, int i_IdCentro, string s_UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/AsignarSucursal", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AsignarSucursalAsync(int i_IdUsuario, int i_IdCentro, string s_UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/AsignarLineaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        string AsignarLineaUsuario(string LoginNetsuite, string sUnidado_clase, string slinea, string sSublinea, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/AsignarLineaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AsignarLineaUsuarioAsync(string LoginNetsuite, string sUnidado_clase, string slinea, string sSublinea, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/InspeccionCambiarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int InspeccionCambiarEstado(string IdInspeccion, int IdEstado, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CoreSIMAdll.org/InspeccionCambiarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InspeccionCambiarEstadoAsync(string IdInspeccion, int IdEstado, int IdUsuario, string UserName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CoreSIMAdll.org/")]
    public partial class UsuarioBE : BaseBE {
        
        private int idPersonalField;
        
        private string loginField;
        
        private string claveField;
        
        private int fotoField;
        
        private int idEquipoField;
        
        private string nroDocumentoField;
        
        private string apellidosyNombresField;
        
        private string areaField;
        
        private string codPersonalField;
        
        private int idCentroOperativoField;
        
        private int nroCentroOperativoField;
        
        private int idContactoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPersonal {
            get {
                return this.idPersonalField;
            }
            set {
                this.idPersonalField = value;
                this.RaisePropertyChanged("IdPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("Foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdEquipo {
            get {
                return this.idEquipoField;
            }
            set {
                this.idEquipoField = value;
                this.RaisePropertyChanged("IdEquipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("NroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ApellidosyNombres {
            get {
                return this.apellidosyNombresField;
            }
            set {
                this.apellidosyNombresField = value;
                this.RaisePropertyChanged("ApellidosyNombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CodPersonal {
            get {
                return this.codPersonalField;
            }
            set {
                this.codPersonalField = value;
                this.RaisePropertyChanged("CodPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdCentroOperativo {
            get {
                return this.idCentroOperativoField;
            }
            set {
                this.idCentroOperativoField = value;
                this.RaisePropertyChanged("IdCentroOperativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int NroCentroOperativo {
            get {
                return this.nroCentroOperativoField;
            }
            set {
                this.nroCentroOperativoField = value;
                this.RaisePropertyChanged("NroCentroOperativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int IdContacto {
            get {
                return this.idContactoField;
            }
            set {
                this.idContactoField = value;
                this.RaisePropertyChanged("IdContacto");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsuarioBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CoreSIMAdll.org/")]
    public partial class BaseBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string sucursalField;
        
        private string estacionField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        private System.DateTime fechaField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado {
            get {
                return this.imgEstadoField;
            }
            set {
                this.imgEstadoField = value;
                this.RaisePropertyChanged("ImgEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado {
            get {
                return this.nombreEstadoField;
            }
            set {
                this.nombreEstadoField = value;
                this.RaisePropertyChanged("NombreEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
                this.RaisePropertyChanged("Estacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdCodigo {
            get {
                return this.idCodigoField;
            }
            set {
                this.idCodigoField = value;
                this.RaisePropertyChanged("IdCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
                this.RaisePropertyChanged("ambiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeguridadSoapChannel : SIMANET_W22R.srvSeguridad.SeguridadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvSeguridad.SeguridadSoap>, SIMANET_W22R.srvSeguridad.SeguridadSoap {
        
        public SeguridadSoapClient() {
        }
        
        public SeguridadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetPerfiles(int IdUser, string UserName) {
            return base.Channel.GetPerfiles(IdUser, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPerfilesAsync(int IdUser, string UserName) {
            return base.Channel.GetPerfilesAsync(IdUser, UserName);
        }
        
        public int ValidateUser(string login, string password) {
            return base.Channel.ValidateUser(login, password);
        }
        
        public System.Threading.Tasks.Task<int> ValidateUserAsync(string login, string password) {
            return base.Channel.ValidateUserAsync(login, password);
        }
        
        public int ValidateUserAD(string login, string password) {
            return base.Channel.ValidateUserAD(login, password);
        }
        
        public System.Threading.Tasks.Task<int> ValidateUserADAsync(string login, string password) {
            return base.Channel.ValidateUserADAsync(login, password);
        }
        
        public bool VerificaCaducidadUser(int IdUsuario) {
            return base.Channel.VerificaCaducidadUser(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> VerificaCaducidadUserAsync(int IdUsuario) {
            return base.Channel.VerificaCaducidadUserAsync(IdUsuario);
        }
        
        public System.Data.DataTable GetOptionsByProfile(int idSystem, int idProfile, string pagina) {
            return base.Channel.GetOptionsByProfile(idSystem, idProfile, pagina);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOptionsByProfileAsync(int idSystem, int idProfile, string pagina) {
            return base.Channel.GetOptionsByProfileAsync(idSystem, idProfile, pagina);
        }
        
        public System.Data.DataTable GetPerfilAccesoDirecto(int idSystem, int idUsuario) {
            return base.Channel.GetPerfilAccesoDirecto(idSystem, idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPerfilAccesoDirectoAsync(int idSystem, int idUsuario) {
            return base.Channel.GetPerfilAccesoDirectoAsync(idSystem, idUsuario);
        }
        
        public SIMANET_W22R.srvSeguridad.UsuarioBE GetDatosUsuario(int idUsuario) {
            return base.Channel.GetDatosUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvSeguridad.UsuarioBE> GetDatosUsuarioAsync(int idUsuario) {
            return base.Channel.GetDatosUsuarioAsync(idUsuario);
        }
        
        public System.Data.DataTable CodigoUsuario(string s_idUsuario) {
            return base.Channel.CodigoUsuario(s_idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CodigoUsuarioAsync(string s_idUsuario) {
            return base.Channel.CodigoUsuarioAsync(s_idUsuario);
        }
        
        public int AsignarSucursal(int i_IdUsuario, int i_IdCentro, string s_UserName) {
            return base.Channel.AsignarSucursal(i_IdUsuario, i_IdCentro, s_UserName);
        }
        
        public System.Threading.Tasks.Task<int> AsignarSucursalAsync(int i_IdUsuario, int i_IdCentro, string s_UserName) {
            return base.Channel.AsignarSucursalAsync(i_IdUsuario, i_IdCentro, s_UserName);
        }
        
        public string AsignarLineaUsuario(string LoginNetsuite, string sUnidado_clase, string slinea, string sSublinea, string UserName) {
            return base.Channel.AsignarLineaUsuario(LoginNetsuite, sUnidado_clase, slinea, sSublinea, UserName);
        }
        
        public System.Threading.Tasks.Task<string> AsignarLineaUsuarioAsync(string LoginNetsuite, string sUnidado_clase, string slinea, string sSublinea, string UserName) {
            return base.Channel.AsignarLineaUsuarioAsync(LoginNetsuite, sUnidado_clase, slinea, sSublinea, UserName);
        }
        
        public int InspeccionCambiarEstado(string IdInspeccion, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.InspeccionCambiarEstado(IdInspeccion, IdEstado, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<int> InspeccionCambiarEstadoAsync(string IdInspeccion, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.InspeccionCambiarEstadoAsync(IdInspeccion, IdEstado, IdUsuario, UserName);
        }
    }
}
