//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionContabilidad {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionContabilidad.ContabilidadSoap")]
    public interface ContabilidadSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_balance_de_comprobacion(string D_MES, string D_PERIODO, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacionAsync(string D_MES, string D_PERIODO, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_10_Columnas_2_Digit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_balance_10_Columnas_2_Digit(string N_CEO, string V_ANIO, string V_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_10_Columnas_2_Digit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_10_Columnas_2_DigitAsync(string N_CEO, string V_ANIO, string V_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion_SUNAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_balance_de_comprobacion_SUNAT(string N_CEO, string V_ANIO, string V_MES, string V_CUENTAINI, string V_CUENTAFIN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion_SUNAT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacion_SUNATAsync(string N_CEO, string V_ANIO, string V_MES, string V_CUENTAINI, string V_CUENTAFIN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion_p", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_balance_de_comprobacion_p(string D_AÑO, string D_MES, string D_MES_AJUSTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion_p", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacion_pAsync(string D_AÑO, string D_MES, string D_MES_AJUSTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_constructivo_mef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_balance_constructivo_mef(string D_AÑO, string D_MES, string D_MES_AJUSTE, string V_CODCEO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_constructivo_mef", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_constructivo_mefAsync(string D_AÑO, string D_MES, string D_MES_AJUSTE, string V_CODCEO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_bal_constructivo_susalud", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_bal_constructivo_susalud(string D_AÑO, string D_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_bal_constructivo_susalud", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_bal_constructivo_susaludAsync(string D_AÑO, string D_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_MaXAuxi_Pend_Det_Conci", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_MaXAuxi_Pend_Det_Conci(string V_Cuenta, string D_Año, string D_Mes, string V_Relacion_Desde, string V_Relacion_Hasta, string V_Documento, string V_Menos_Subdiario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_MaXAuxi_Pend_Det_Conci", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_MaXAuxi_Pend_Det_ConciAsync(string V_Cuenta, string D_Año, string D_Mes, string V_Relacion_Desde, string V_Relacion_Hasta, string V_Documento, string V_Menos_Subdiario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion_3_Digitos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_balance_de_comprobacion_3_Digitos(string D_PERIODO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_balance_de_comprobacion_3_Digitos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacion_3_DigitosAsync(string D_PERIODO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_analisis_cuentas_nat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_analisis_cuentas_nat(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_CTA_MAYOR_DESDE, string V_CTA_MAYOR_HASTA, string V_C_COSTO_DESDE, string V_C_COSTO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_analisis_cuentas_nat", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_analisis_cuentas_natAsync(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_CTA_MAYOR_DESDE, string V_CTA_MAYOR_HASTA, string V_C_COSTO_DESDE, string V_C_COSTO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_pend_rel_res", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxi_pend_rel_res(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_pend_rel_res", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_pend_rel_resAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conci_bancaria_resumen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_conci_bancaria_resumen(string D_AÑO, string D_MES, string V_COD_BCO, string V_CUENTA_CORRIENTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conci_bancaria_resumen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_conci_bancaria_resumenAsync(string D_AÑO, string D_MES, string V_COD_BCO, string V_CUENTA_CORRIENTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_cuenta_resumen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxi_cuenta_resumen(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_cuenta_resumen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_cuenta_resumenAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_Rela_Resu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxi_Rela_Resu(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_Rela_Resu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_Rela_ResuAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Estado_del_Proceso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Estado_del_Proceso(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Estado_del_Proceso", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Estado_del_ProcesoAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_Resumen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_Resumen(string V_Cuenta_Desde, string V_Cuenta_Hasta, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_Resumen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_ResumenAsync(string V_Cuenta_Desde, string V_Cuenta_Hasta, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_centros_de_costo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_centros_de_costo(string V_CENTRO_OPERATIVO, string V_GRUPO_CC_DESDE, string V_GRUPO_CC_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_centros_de_costo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_centros_de_costoAsync(string V_CENTRO_OPERATIVO, string V_GRUPO_CC_DESDE, string V_GRUPO_CC_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_tipo_de_cambio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_tipo_de_cambio(string V_ANIO, string V_CODMND, string V_MESFIN, string V_MESINI, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_tipo_de_cambio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_tipo_de_cambioAsync(string V_ANIO, string V_CODMND, string V_MESFIN, string V_MESINI, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_subdiario_por_cuenta_res", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_subdiario_por_cuenta_res(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA, string V_SUBDIARIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_subdiario_por_cuenta_res", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_subdiario_por_cuenta_resAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA, string V_SUBDIARIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mov_cuenta_91_92", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mov_cuenta_91_92(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mov_cuenta_91_92", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mov_cuenta_91_92Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_plan_cuentas_pcge_2019", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_plan_cuentas_pcge_2019(string V_CTA_FIN, string V_CTA_INI, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_plan_cuentas_pcge_2019", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_plan_cuentas_pcge_2019Async(string V_CTA_FIN, string V_CTA_INI, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_cuenta_96", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_movimiento_cuenta_96(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_cuenta_96", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_movimiento_cuenta_96Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_asientos_por_subdiario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_asientos_por_subdiario(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_asientos_por_subdiario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_asientos_por_subdiarioAsync(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_pend_doc_res", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxi_pend_doc_res(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_pend_doc_res", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_pend_doc_resAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_doc_resu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxi_doc_resu(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_doc_resu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_doc_resuAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_cuenta_97", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_movimiento_cuenta_97(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_cuenta_97", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_movimiento_cuenta_97Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxiliar_detalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxiliar_detalle(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxiliar_detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxiliar_detalleAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxiliar_pend_deta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxiliar_pend_deta(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxiliar_pend_deta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxiliar_pend_detaAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_por_cuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_movimiento_por_cuenta(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_por_cuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_movimiento_por_cuentaAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_por_cuenta2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_movimiento_por_cuenta2(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_movimiento_por_cuenta2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_movimiento_por_cuenta2Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_asientos_por_subdiario_02", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_asientos_por_subdiario_02(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CODDIV, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_NROOTS, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_asientos_por_subdiario_02", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_asientos_por_subdiario_02Async(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CODDIV, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_NROOTS, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_asientos_subdiario_resu_c", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_asientos_subdiario_resu_c(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_asientos_subdiario_resu_c", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_asientos_subdiario_resu_cAsync(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_tabulado_por_subdiarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_tabulado_por_subdiarios(string V_ANIO, string V_CUENTA, string V_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_tabulado_por_subdiarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_tabulado_por_subdiariosAsync(string V_ANIO, string V_CUENTA, string V_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_canceladas_det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_mayor_auxi_canceladas_det(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_mayor_auxi_canceladas_det", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_canceladas_detAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_voucher_por_documento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_voucher_por_documento(string V_NUMERO, string V_PROVEEDOR, string V_SERIE, string V_TIPO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_voucher_por_documento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_voucher_por_documentoAsync(string V_NUMERO, string V_PROVEEDOR, string V_SERIE, string V_TIPO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_registro_retenciones_suna", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_registro_retenciones_suna(string N_CEO, string V_ANIO, string V_NROMES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_registro_retenciones_suna", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_registro_retenciones_sunaAsync(string N_CEO, string V_ANIO, string V_NROMES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_pagos_por_cuenta_detraccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_pagos_por_cuenta_detraccion(string N_CEO, string V_ANIO, string V_MESFIN, string V_MESINI, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_pagos_por_cuenta_detraccion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_pagos_por_cuenta_detraccionAsync(string N_CEO, string V_ANIO, string V_MESFIN, string V_MESINI, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_registro_de_ventas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_registro_de_ventas(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_LINEA_NEGOCIO, string V_ORIGEN, string V_SERIE, string V_TIPO_DOCUMENTO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_registro_de_ventas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_registro_de_ventasAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_LINEA_NEGOCIO, string V_ORIGEN, string V_SERIE, string V_TIPO_DOCUMENTO, string UserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContabilidadSoapChannel : SIMANET_W22R.srvGestionContabilidad.ContabilidadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContabilidadSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionContabilidad.ContabilidadSoap>, SIMANET_W22R.srvGestionContabilidad.ContabilidadSoap {
        
        public ContabilidadSoapClient() {
        }
        
        public ContabilidadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContabilidadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContabilidadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContabilidadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Listar_balance_de_comprobacion(string D_MES, string D_PERIODO, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion(D_MES, D_PERIODO, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacionAsync(string D_MES, string D_PERIODO, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName) {
            return base.Channel.Listar_balance_de_comprobacionAsync(D_MES, D_PERIODO, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_balance_10_Columnas_2_Digit(string N_CEO, string V_ANIO, string V_MES, string UserName) {
            return base.Channel.Listar_balance_10_Columnas_2_Digit(N_CEO, V_ANIO, V_MES, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_10_Columnas_2_DigitAsync(string N_CEO, string V_ANIO, string V_MES, string UserName) {
            return base.Channel.Listar_balance_10_Columnas_2_DigitAsync(N_CEO, V_ANIO, V_MES, UserName);
        }
        
        public System.Data.DataTable Listar_balance_de_comprobacion_SUNAT(string N_CEO, string V_ANIO, string V_MES, string V_CUENTAINI, string V_CUENTAFIN, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion_SUNAT(N_CEO, V_ANIO, V_MES, V_CUENTAINI, V_CUENTAFIN, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacion_SUNATAsync(string N_CEO, string V_ANIO, string V_MES, string V_CUENTAINI, string V_CUENTAFIN, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion_SUNATAsync(N_CEO, V_ANIO, V_MES, V_CUENTAINI, V_CUENTAFIN, UserName);
        }
        
        public System.Data.DataTable Listar_balance_de_comprobacion_p(string D_AÑO, string D_MES, string D_MES_AJUSTE, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion_p(D_AÑO, D_MES, D_MES_AJUSTE, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacion_pAsync(string D_AÑO, string D_MES, string D_MES_AJUSTE, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion_pAsync(D_AÑO, D_MES, D_MES_AJUSTE, UserName);
        }
        
        public System.Data.DataTable Listar_balance_constructivo_mef(string D_AÑO, string D_MES, string D_MES_AJUSTE, string V_CODCEO, string UserName) {
            return base.Channel.Listar_balance_constructivo_mef(D_AÑO, D_MES, D_MES_AJUSTE, V_CODCEO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_constructivo_mefAsync(string D_AÑO, string D_MES, string D_MES_AJUSTE, string V_CODCEO, string UserName) {
            return base.Channel.Listar_balance_constructivo_mefAsync(D_AÑO, D_MES, D_MES_AJUSTE, V_CODCEO, UserName);
        }
        
        public System.Data.DataTable Listar_bal_constructivo_susalud(string D_AÑO, string D_MES, string UserName) {
            return base.Channel.Listar_bal_constructivo_susalud(D_AÑO, D_MES, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_bal_constructivo_susaludAsync(string D_AÑO, string D_MES, string UserName) {
            return base.Channel.Listar_bal_constructivo_susaludAsync(D_AÑO, D_MES, UserName);
        }
        
        public System.Data.DataTable Listar_MaXAuxi_Pend_Det_Conci(string V_Cuenta, string D_Año, string D_Mes, string V_Relacion_Desde, string V_Relacion_Hasta, string V_Documento, string V_Menos_Subdiario, string UserName) {
            return base.Channel.Listar_MaXAuxi_Pend_Det_Conci(V_Cuenta, D_Año, D_Mes, V_Relacion_Desde, V_Relacion_Hasta, V_Documento, V_Menos_Subdiario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_MaXAuxi_Pend_Det_ConciAsync(string V_Cuenta, string D_Año, string D_Mes, string V_Relacion_Desde, string V_Relacion_Hasta, string V_Documento, string V_Menos_Subdiario, string UserName) {
            return base.Channel.Listar_MaXAuxi_Pend_Det_ConciAsync(V_Cuenta, D_Año, D_Mes, V_Relacion_Desde, V_Relacion_Hasta, V_Documento, V_Menos_Subdiario, UserName);
        }
        
        public System.Data.DataTable Listar_balance_de_comprobacion_3_Digitos(string D_PERIODO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion_3_Digitos(D_PERIODO, D_MES, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_balance_de_comprobacion_3_DigitosAsync(string D_PERIODO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName) {
            return base.Channel.Listar_balance_de_comprobacion_3_DigitosAsync(D_PERIODO, D_MES, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_analisis_cuentas_nat(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_CTA_MAYOR_DESDE, string V_CTA_MAYOR_HASTA, string V_C_COSTO_DESDE, string V_C_COSTO_HASTA, string UserName) {
            return base.Channel.Listar_analisis_cuentas_nat(D_AÑO, D_MES_DESDE, D_MES_HASTA, V_CENTRO_OPERATIVO, V_CTA_MAYOR_DESDE, V_CTA_MAYOR_HASTA, V_C_COSTO_DESDE, V_C_COSTO_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_analisis_cuentas_natAsync(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_CTA_MAYOR_DESDE, string V_CTA_MAYOR_HASTA, string V_C_COSTO_DESDE, string V_C_COSTO_HASTA, string UserName) {
            return base.Channel.Listar_analisis_cuentas_natAsync(D_AÑO, D_MES_DESDE, D_MES_HASTA, V_CENTRO_OPERATIVO, V_CTA_MAYOR_DESDE, V_CTA_MAYOR_HASTA, V_C_COSTO_DESDE, V_C_COSTO_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxi_pend_rel_res(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_pend_rel_res(D_AÑO, D_MES, V_CUENTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_pend_rel_resAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_pend_rel_resAsync(D_AÑO, D_MES, V_CUENTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_conci_bancaria_resumen(string D_AÑO, string D_MES, string V_COD_BCO, string V_CUENTA_CORRIENTE, string UserName) {
            return base.Channel.Listar_conci_bancaria_resumen(D_AÑO, D_MES, V_COD_BCO, V_CUENTA_CORRIENTE, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_conci_bancaria_resumenAsync(string D_AÑO, string D_MES, string V_COD_BCO, string V_CUENTA_CORRIENTE, string UserName) {
            return base.Channel.Listar_conci_bancaria_resumenAsync(D_AÑO, D_MES, V_COD_BCO, V_CUENTA_CORRIENTE, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxi_cuenta_resumen(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_cuenta_resumen(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_cuenta_resumenAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_cuenta_resumenAsync(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxi_Rela_Resu(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_Rela_Resu(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_Rela_ResuAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_Rela_ResuAsync(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_Estado_del_Proceso(string UserName) {
            return base.Channel.Listar_Estado_del_Proceso(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Estado_del_ProcesoAsync(string UserName) {
            return base.Channel.Listar_Estado_del_ProcesoAsync(UserName);
        }
        
        public System.Data.DataTable Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_Resumen(string V_Cuenta_Desde, string V_Cuenta_Hasta, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_Resumen(V_Cuenta_Desde, V_Cuenta_Hasta, D_Año, D_Mes, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_ResumenAsync(string V_Cuenta_Desde, string V_Cuenta_Hasta, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Mayor_Auxiliar_Pendientes_por_Cuenta_ResumenAsync(V_Cuenta_Desde, V_Cuenta_Hasta, D_Año, D_Mes, UserName);
        }
        
        public System.Data.DataTable Listar_centros_de_costo(string V_CENTRO_OPERATIVO, string V_GRUPO_CC_DESDE, string V_GRUPO_CC_HASTA, string UserName) {
            return base.Channel.Listar_centros_de_costo(V_CENTRO_OPERATIVO, V_GRUPO_CC_DESDE, V_GRUPO_CC_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_centros_de_costoAsync(string V_CENTRO_OPERATIVO, string V_GRUPO_CC_DESDE, string V_GRUPO_CC_HASTA, string UserName) {
            return base.Channel.Listar_centros_de_costoAsync(V_CENTRO_OPERATIVO, V_GRUPO_CC_DESDE, V_GRUPO_CC_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_tipo_de_cambio(string V_ANIO, string V_CODMND, string V_MESFIN, string V_MESINI, string UserName) {
            return base.Channel.Listar_tipo_de_cambio(V_ANIO, V_CODMND, V_MESFIN, V_MESINI, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_tipo_de_cambioAsync(string V_ANIO, string V_CODMND, string V_MESFIN, string V_MESINI, string UserName) {
            return base.Channel.Listar_tipo_de_cambioAsync(V_ANIO, V_CODMND, V_MESFIN, V_MESINI, UserName);
        }
        
        public System.Data.DataTable Listar_subdiario_por_cuenta_res(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA, string V_SUBDIARIO, string UserName) {
            return base.Channel.Listar_subdiario_por_cuenta_res(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_CUENTA, V_SUBDIARIO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_subdiario_por_cuenta_resAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CUENTA, string V_SUBDIARIO, string UserName) {
            return base.Channel.Listar_subdiario_por_cuenta_resAsync(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_CUENTA, V_SUBDIARIO, UserName);
        }
        
        public System.Data.DataTable Listar_mov_cuenta_91_92(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName) {
            return base.Channel.Listar_mov_cuenta_91_92(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mov_cuenta_91_92Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName) {
            return base.Channel.Listar_mov_cuenta_91_92Async(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_plan_cuentas_pcge_2019(string V_CTA_FIN, string V_CTA_INI, string UserName) {
            return base.Channel.Listar_plan_cuentas_pcge_2019(V_CTA_FIN, V_CTA_INI, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_plan_cuentas_pcge_2019Async(string V_CTA_FIN, string V_CTA_INI, string UserName) {
            return base.Channel.Listar_plan_cuentas_pcge_2019Async(V_CTA_FIN, V_CTA_INI, UserName);
        }
        
        public System.Data.DataTable Listar_movimiento_cuenta_96(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName) {
            return base.Channel.Listar_movimiento_cuenta_96(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_movimiento_cuenta_96Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName) {
            return base.Channel.Listar_movimiento_cuenta_96Async(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_asientos_por_subdiario(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName) {
            return base.Channel.Listar_asientos_por_subdiario(D_DIAFIN, D_DIAINI, N_CEO, V_ANIO, V_ASIENTOFIN, V_ASIENTOINI, V_CENTROFIN, V_CENTROINI, V_CUENTAFIN, V_CUENTAINI, V_MES, V_SUBDIARIO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_asientos_por_subdiarioAsync(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName) {
            return base.Channel.Listar_asientos_por_subdiarioAsync(D_DIAFIN, D_DIAINI, N_CEO, V_ANIO, V_ASIENTOFIN, V_ASIENTOINI, V_CENTROFIN, V_CENTROINI, V_CUENTAFIN, V_CUENTAINI, V_MES, V_SUBDIARIO, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxi_pend_doc_res(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_pend_doc_res(D_AÑO, D_MES, V_CUENTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_pend_doc_resAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_pend_doc_resAsync(D_AÑO, D_MES, V_CUENTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxi_doc_resu(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_doc_resu(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_doc_resuAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_doc_resuAsync(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_movimiento_cuenta_97(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName) {
            return base.Channel.Listar_movimiento_cuenta_97(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_movimiento_cuenta_97Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string UserName) {
            return base.Channel.Listar_movimiento_cuenta_97Async(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxiliar_detalle(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxiliar_detalle(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxiliar_detalleAsync(string D_AÑO, string D_MES, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxiliar_detalleAsync(D_AÑO, D_MES, V_CUENTA_DESDE, V_CUENTA_HASTA, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxiliar_pend_deta(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION, string UserName) {
            return base.Channel.Listar_mayor_auxiliar_pend_deta(D_AÑO, D_MES, V_CUENTA, V_DOCUMENTO, V_RELACION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxiliar_pend_detaAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION, string UserName) {
            return base.Channel.Listar_mayor_auxiliar_pend_detaAsync(D_AÑO, D_MES, V_CUENTA, V_DOCUMENTO, V_RELACION, UserName);
        }
        
        public System.Data.DataTable Listar_movimiento_por_cuenta(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName) {
            return base.Channel.Listar_movimiento_por_cuenta(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, V_CC, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_movimiento_por_cuentaAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName) {
            return base.Channel.Listar_movimiento_por_cuentaAsync(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, V_CC, UserName);
        }
        
        public string Listar_movimiento_por_cuenta2(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName) {
            return base.Channel.Listar_movimiento_por_cuenta2(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, V_CC, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_movimiento_por_cuenta2Async(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CUENTA_DESDE, string V_CUENTA_HASTA, string V_SUBDIARIO_DESDE, string V_SUBDIARIO_HASTA, string V_CC, string UserName) {
            return base.Channel.Listar_movimiento_por_cuenta2Async(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CUENTA_DESDE, V_CUENTA_HASTA, V_SUBDIARIO_DESDE, V_SUBDIARIO_HASTA, V_CC, UserName);
        }
        
        public System.Data.DataTable Listar_asientos_por_subdiario_02(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CODDIV, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_NROOTS, string UserName) {
            return base.Channel.Listar_asientos_por_subdiario_02(D_DIAFIN, D_DIAINI, N_CEO, V_ANIO, V_ASIENTOFIN, V_ASIENTOINI, V_CENTROFIN, V_CENTROINI, V_CODDIV, V_CUENTAFIN, V_CUENTAINI, V_MES, V_NROOTS, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_asientos_por_subdiario_02Async(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CODDIV, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_NROOTS, string UserName) {
            return base.Channel.Listar_asientos_por_subdiario_02Async(D_DIAFIN, D_DIAINI, N_CEO, V_ANIO, V_ASIENTOFIN, V_ASIENTOINI, V_CENTROFIN, V_CENTROINI, V_CODDIV, V_CUENTAFIN, V_CUENTAINI, V_MES, V_NROOTS, UserName);
        }
        
        public System.Data.DataTable Listar_asientos_subdiario_resu_c(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName) {
            return base.Channel.Listar_asientos_subdiario_resu_c(D_DIAFIN, D_DIAINI, N_CEO, V_ANIO, V_ASIENTOFIN, V_ASIENTOINI, V_CENTROFIN, V_CENTROINI, V_CUENTAFIN, V_CUENTAINI, V_MES, V_SUBDIARIO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_asientos_subdiario_resu_cAsync(string D_DIAFIN, string D_DIAINI, string N_CEO, string V_ANIO, string V_ASIENTOFIN, string V_ASIENTOINI, string V_CENTROFIN, string V_CENTROINI, string V_CUENTAFIN, string V_CUENTAINI, string V_MES, string V_SUBDIARIO, string UserName) {
            return base.Channel.Listar_asientos_subdiario_resu_cAsync(D_DIAFIN, D_DIAINI, N_CEO, V_ANIO, V_ASIENTOFIN, V_ASIENTOINI, V_CENTROFIN, V_CENTROINI, V_CUENTAFIN, V_CUENTAINI, V_MES, V_SUBDIARIO, UserName);
        }
        
        public System.Data.DataTable Listar_tabulado_por_subdiarios(string V_ANIO, string V_CUENTA, string V_MES, string UserName) {
            return base.Channel.Listar_tabulado_por_subdiarios(V_ANIO, V_CUENTA, V_MES, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_tabulado_por_subdiariosAsync(string V_ANIO, string V_CUENTA, string V_MES, string UserName) {
            return base.Channel.Listar_tabulado_por_subdiariosAsync(V_ANIO, V_CUENTA, V_MES, UserName);
        }
        
        public System.Data.DataTable Listar_mayor_auxi_canceladas_det(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_canceladas_det(D_AÑO, D_MES, V_CUENTA, V_DOCUMENTO, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_mayor_auxi_canceladas_detAsync(string D_AÑO, string D_MES, string V_CUENTA, string V_DOCUMENTO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_mayor_auxi_canceladas_detAsync(D_AÑO, D_MES, V_CUENTA, V_DOCUMENTO, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_voucher_por_documento(string V_NUMERO, string V_PROVEEDOR, string V_SERIE, string V_TIPO, string UserName) {
            return base.Channel.Listar_voucher_por_documento(V_NUMERO, V_PROVEEDOR, V_SERIE, V_TIPO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_voucher_por_documentoAsync(string V_NUMERO, string V_PROVEEDOR, string V_SERIE, string V_TIPO, string UserName) {
            return base.Channel.Listar_voucher_por_documentoAsync(V_NUMERO, V_PROVEEDOR, V_SERIE, V_TIPO, UserName);
        }
        
        public System.Data.DataTable Listar_registro_retenciones_suna(string N_CEO, string V_ANIO, string V_NROMES, string UserName) {
            return base.Channel.Listar_registro_retenciones_suna(N_CEO, V_ANIO, V_NROMES, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_registro_retenciones_sunaAsync(string N_CEO, string V_ANIO, string V_NROMES, string UserName) {
            return base.Channel.Listar_registro_retenciones_sunaAsync(N_CEO, V_ANIO, V_NROMES, UserName);
        }
        
        public System.Data.DataTable Listar_pagos_por_cuenta_detraccion(string N_CEO, string V_ANIO, string V_MESFIN, string V_MESINI, string UserName) {
            return base.Channel.Listar_pagos_por_cuenta_detraccion(N_CEO, V_ANIO, V_MESFIN, V_MESINI, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_pagos_por_cuenta_detraccionAsync(string N_CEO, string V_ANIO, string V_MESFIN, string V_MESINI, string UserName) {
            return base.Channel.Listar_pagos_por_cuenta_detraccionAsync(N_CEO, V_ANIO, V_MESFIN, V_MESINI, UserName);
        }
        
        public System.Data.DataTable Listar_registro_de_ventas(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_LINEA_NEGOCIO, string V_ORIGEN, string V_SERIE, string V_TIPO_DOCUMENTO, string UserName) {
            return base.Channel.Listar_registro_de_ventas(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_CONCEPTO, V_LINEA_NEGOCIO, V_ORIGEN, V_SERIE, V_TIPO_DOCUMENTO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_registro_de_ventasAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_LINEA_NEGOCIO, string V_ORIGEN, string V_SERIE, string V_TIPO_DOCUMENTO, string UserName) {
            return base.Channel.Listar_registro_de_ventasAsync(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_CONCEPTO, V_LINEA_NEGOCIO, V_ORIGEN, V_SERIE, V_TIPO_DOCUMENTO, UserName);
        }
    }
}
