//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionSeguridadPlanta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api-netsuite.sima.com.pe/seguridadplanta", ConfigurationName="srvGestionSeguridadPlanta.VisitasSoap")]
    public interface VisitasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ListarTodos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ListarTodos(string S_PROGRAMACION, string S_PERIODO, string S_TIPOPROGRA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ListarTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ListarTodosAsync(string S_PROGRAMACION, string S_PERIODO, string S_TIPOPROGRA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ListarProgramacionVisita_JSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ListarProgramacionVisita_JSON(string Id1, string Id2, string Id3, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ListarProgramacionVisita_JSON", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ListarProgramacionVisita_JSONAsync(string Id1, string Id2, string Id3, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ProgramacionVisita_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ProgramacionVisita_Ins(string IdTipoVisita, string IdEntidad, string IdArea, string FechaInicio, string FechaTermino, string HoraInicio, string HoraTermino, string IdCIASeguros, string NroPoliza, string Observaciones, string IdUsuarioRegistro, string TipoProgramacion, string IdUsuarioAprobacion, string IdEstado, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ProgramacionVisita_Ins", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ProgramacionVisita_InsAsync(string IdTipoVisita, string IdEntidad, string IdArea, string FechaInicio, string FechaTermino, string HoraInicio, string HoraTermino, string IdCIASeguros, string NroPoliza, string Observaciones, string IdUsuarioRegistro, string TipoProgramacion, string IdUsuarioAprobacion, string IdEstado, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ProgramacionVisitas_Ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        string ProgramacionVisitas_Ins(SIMANET_W22R.srvGestionSeguridadPlanta.ProgramacionBE oProgramacionBE, string LstCorreos, string LstAnexos);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api-netsuite.sima.com.pe/seguridadplanta/ProgramacionVisitas_Ins", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ProgramacionVisitas_InsAsync(SIMANET_W22R.srvGestionSeguridadPlanta.ProgramacionBE oProgramacionBE, string LstCorreos, string LstAnexos);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api-netsuite.sima.com.pe/seguridadplanta")]
    public partial class ProgramacionBE : BaseBE {
        
        private int nRO_PROGRAMACIONField;
        
        private int pERIODOField;
        
        private int iD_TABLA_TIPO_ENTIDADField;
        
        private int iD_TIPO_VISITAField;
        
        private int iD_ENTIDADField;
        
        private System.Nullable<int> iD_JEFE_PROYECTOField;
        
        private string nRO_REGISTRO_INGRESOField;
        
        private string nRO_DOCUMENTO_REFField;
        
        private System.DateTime fECHA_INICIOField;
        
        private System.DateTime fECHA_TERMINOField;
        
        private string hORA_INICIOField;
        
        private string hORA_TERMINOField;
        
        private int iD_TABLA_CIA_SEGUROSField;
        
        private int iD_CIA_SEGUROSField;
        
        private string nRO_POLIZAField;
        
        private System.Nullable<System.DateTime> fECHA_INICIO_POLIZAField;
        
        private System.Nullable<System.DateTime> fECHA_TERMINO_POLIZAField;
        
        private string nRO_PENSION_POLIZAField;
        
        private string nRO_SALUD_POLIZAField;
        
        private string tRABAJOS_A_REALIZARField;
        
        private System.Nullable<int> iD_TABLA_LUGAR_TRABAJOField;
        
        private System.Nullable<int> iD_LUGAR_TRABAJOField;
        
        private string nOMBRE_NAVEField;
        
        private string cONTACTO_NOMBRESField;
        
        private string oBSERVACIONESField;
        
        private int iD_TABLA_ESTADOField;
        
        private int iD_ESTADOField;
        
        private int iD_USUARIO_REGISTROField;
        
        private System.Nullable<int> iD_USUARIO_MODIFICACIONField;
        
        private System.Nullable<int> iD_USUARIO_ELIMINACIONField;
        
        private System.DateTime fECHA_REGISTROField;
        
        private System.Nullable<System.DateTime> fECHA_MODIFICACIONField;
        
        private System.Nullable<System.DateTime> fECHA_ELIMINACIONField;
        
        private int tIPO_PROGRAMACIONField;
        
        private System.Nullable<int> iD_USUARIO_APROBACIONField;
        
        private System.Nullable<int> iNTERF_ENVIADOField;
        
        private string nRO_DOCField;
        
        private string iD_OSField;
        
        private string pC_IPField;
        
        private System.Nullable<int> nO_PROGField;
        
        private System.Nullable<System.DateTime> fECHA_INICIO_POLIZA_SField;
        
        private System.Nullable<System.DateTime> fECHA_TERMINO_POLIZA_SField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NRO_PROGRAMACION {
            get {
                return this.nRO_PROGRAMACIONField;
            }
            set {
                this.nRO_PROGRAMACIONField = value;
                this.RaisePropertyChanged("NRO_PROGRAMACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
                this.RaisePropertyChanged("PERIODO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ID_TABLA_TIPO_ENTIDAD {
            get {
                return this.iD_TABLA_TIPO_ENTIDADField;
            }
            set {
                this.iD_TABLA_TIPO_ENTIDADField = value;
                this.RaisePropertyChanged("ID_TABLA_TIPO_ENTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ID_TIPO_VISITA {
            get {
                return this.iD_TIPO_VISITAField;
            }
            set {
                this.iD_TIPO_VISITAField = value;
                this.RaisePropertyChanged("ID_TIPO_VISITA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID_ENTIDAD {
            get {
                return this.iD_ENTIDADField;
            }
            set {
                this.iD_ENTIDADField = value;
                this.RaisePropertyChanged("ID_ENTIDAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> ID_JEFE_PROYECTO {
            get {
                return this.iD_JEFE_PROYECTOField;
            }
            set {
                this.iD_JEFE_PROYECTOField = value;
                this.RaisePropertyChanged("ID_JEFE_PROYECTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NRO_REGISTRO_INGRESO {
            get {
                return this.nRO_REGISTRO_INGRESOField;
            }
            set {
                this.nRO_REGISTRO_INGRESOField = value;
                this.RaisePropertyChanged("NRO_REGISTRO_INGRESO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NRO_DOCUMENTO_REF {
            get {
                return this.nRO_DOCUMENTO_REFField;
            }
            set {
                this.nRO_DOCUMENTO_REFField = value;
                this.RaisePropertyChanged("NRO_DOCUMENTO_REF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime FECHA_INICIO {
            get {
                return this.fECHA_INICIOField;
            }
            set {
                this.fECHA_INICIOField = value;
                this.RaisePropertyChanged("FECHA_INICIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime FECHA_TERMINO {
            get {
                return this.fECHA_TERMINOField;
            }
            set {
                this.fECHA_TERMINOField = value;
                this.RaisePropertyChanged("FECHA_TERMINO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string HORA_INICIO {
            get {
                return this.hORA_INICIOField;
            }
            set {
                this.hORA_INICIOField = value;
                this.RaisePropertyChanged("HORA_INICIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string HORA_TERMINO {
            get {
                return this.hORA_TERMINOField;
            }
            set {
                this.hORA_TERMINOField = value;
                this.RaisePropertyChanged("HORA_TERMINO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int ID_TABLA_CIA_SEGUROS {
            get {
                return this.iD_TABLA_CIA_SEGUROSField;
            }
            set {
                this.iD_TABLA_CIA_SEGUROSField = value;
                this.RaisePropertyChanged("ID_TABLA_CIA_SEGUROS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ID_CIA_SEGUROS {
            get {
                return this.iD_CIA_SEGUROSField;
            }
            set {
                this.iD_CIA_SEGUROSField = value;
                this.RaisePropertyChanged("ID_CIA_SEGUROS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string NRO_POLIZA {
            get {
                return this.nRO_POLIZAField;
            }
            set {
                this.nRO_POLIZAField = value;
                this.RaisePropertyChanged("NRO_POLIZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> FECHA_INICIO_POLIZA {
            get {
                return this.fECHA_INICIO_POLIZAField;
            }
            set {
                this.fECHA_INICIO_POLIZAField = value;
                this.RaisePropertyChanged("FECHA_INICIO_POLIZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> FECHA_TERMINO_POLIZA {
            get {
                return this.fECHA_TERMINO_POLIZAField;
            }
            set {
                this.fECHA_TERMINO_POLIZAField = value;
                this.RaisePropertyChanged("FECHA_TERMINO_POLIZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NRO_PENSION_POLIZA {
            get {
                return this.nRO_PENSION_POLIZAField;
            }
            set {
                this.nRO_PENSION_POLIZAField = value;
                this.RaisePropertyChanged("NRO_PENSION_POLIZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string NRO_SALUD_POLIZA {
            get {
                return this.nRO_SALUD_POLIZAField;
            }
            set {
                this.nRO_SALUD_POLIZAField = value;
                this.RaisePropertyChanged("NRO_SALUD_POLIZA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string TRABAJOS_A_REALIZAR {
            get {
                return this.tRABAJOS_A_REALIZARField;
            }
            set {
                this.tRABAJOS_A_REALIZARField = value;
                this.RaisePropertyChanged("TRABAJOS_A_REALIZAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> ID_TABLA_LUGAR_TRABAJO {
            get {
                return this.iD_TABLA_LUGAR_TRABAJOField;
            }
            set {
                this.iD_TABLA_LUGAR_TRABAJOField = value;
                this.RaisePropertyChanged("ID_TABLA_LUGAR_TRABAJO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> ID_LUGAR_TRABAJO {
            get {
                return this.iD_LUGAR_TRABAJOField;
            }
            set {
                this.iD_LUGAR_TRABAJOField = value;
                this.RaisePropertyChanged("ID_LUGAR_TRABAJO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string NOMBRE_NAVE {
            get {
                return this.nOMBRE_NAVEField;
            }
            set {
                this.nOMBRE_NAVEField = value;
                this.RaisePropertyChanged("NOMBRE_NAVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CONTACTO_NOMBRES {
            get {
                return this.cONTACTO_NOMBRESField;
            }
            set {
                this.cONTACTO_NOMBRESField = value;
                this.RaisePropertyChanged("CONTACTO_NOMBRES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string OBSERVACIONES {
            get {
                return this.oBSERVACIONESField;
            }
            set {
                this.oBSERVACIONESField = value;
                this.RaisePropertyChanged("OBSERVACIONES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int ID_TABLA_ESTADO {
            get {
                return this.iD_TABLA_ESTADOField;
            }
            set {
                this.iD_TABLA_ESTADOField = value;
                this.RaisePropertyChanged("ID_TABLA_ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int ID_ESTADO {
            get {
                return this.iD_ESTADOField;
            }
            set {
                this.iD_ESTADOField = value;
                this.RaisePropertyChanged("ID_ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int ID_USUARIO_REGISTRO {
            get {
                return this.iD_USUARIO_REGISTROField;
            }
            set {
                this.iD_USUARIO_REGISTROField = value;
                this.RaisePropertyChanged("ID_USUARIO_REGISTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ID_USUARIO_MODIFICACION {
            get {
                return this.iD_USUARIO_MODIFICACIONField;
            }
            set {
                this.iD_USUARIO_MODIFICACIONField = value;
                this.RaisePropertyChanged("ID_USUARIO_MODIFICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> ID_USUARIO_ELIMINACION {
            get {
                return this.iD_USUARIO_ELIMINACIONField;
            }
            set {
                this.iD_USUARIO_ELIMINACIONField = value;
                this.RaisePropertyChanged("ID_USUARIO_ELIMINACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public System.DateTime FECHA_REGISTRO {
            get {
                return this.fECHA_REGISTROField;
            }
            set {
                this.fECHA_REGISTROField = value;
                this.RaisePropertyChanged("FECHA_REGISTRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<System.DateTime> FECHA_MODIFICACION {
            get {
                return this.fECHA_MODIFICACIONField;
            }
            set {
                this.fECHA_MODIFICACIONField = value;
                this.RaisePropertyChanged("FECHA_MODIFICACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<System.DateTime> FECHA_ELIMINACION {
            get {
                return this.fECHA_ELIMINACIONField;
            }
            set {
                this.fECHA_ELIMINACIONField = value;
                this.RaisePropertyChanged("FECHA_ELIMINACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public int TIPO_PROGRAMACION {
            get {
                return this.tIPO_PROGRAMACIONField;
            }
            set {
                this.tIPO_PROGRAMACIONField = value;
                this.RaisePropertyChanged("TIPO_PROGRAMACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<int> ID_USUARIO_APROBACION {
            get {
                return this.iD_USUARIO_APROBACIONField;
            }
            set {
                this.iD_USUARIO_APROBACIONField = value;
                this.RaisePropertyChanged("ID_USUARIO_APROBACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<int> INTERF_ENVIADO {
            get {
                return this.iNTERF_ENVIADOField;
            }
            set {
                this.iNTERF_ENVIADOField = value;
                this.RaisePropertyChanged("INTERF_ENVIADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string NRO_DOC {
            get {
                return this.nRO_DOCField;
            }
            set {
                this.nRO_DOCField = value;
                this.RaisePropertyChanged("NRO_DOC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string ID_OS {
            get {
                return this.iD_OSField;
            }
            set {
                this.iD_OSField = value;
                this.RaisePropertyChanged("ID_OS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string PC_IP {
            get {
                return this.pC_IPField;
            }
            set {
                this.pC_IPField = value;
                this.RaisePropertyChanged("PC_IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<int> NO_PROG {
            get {
                return this.nO_PROGField;
            }
            set {
                this.nO_PROGField = value;
                this.RaisePropertyChanged("NO_PROG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<System.DateTime> FECHA_INICIO_POLIZA_S {
            get {
                return this.fECHA_INICIO_POLIZA_SField;
            }
            set {
                this.fECHA_INICIO_POLIZA_SField = value;
                this.RaisePropertyChanged("FECHA_INICIO_POLIZA_S");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public System.Nullable<System.DateTime> FECHA_TERMINO_POLIZA_S {
            get {
                return this.fECHA_TERMINO_POLIZA_SField;
            }
            set {
                this.fECHA_TERMINO_POLIZA_SField = value;
                this.RaisePropertyChanged("FECHA_TERMINO_POLIZA_S");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProgramacionBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api-netsuite.sima.com.pe/seguridadplanta")]
    public partial class BaseBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string sucursalField;
        
        private string estacionField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        private System.DateTime fechaField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado {
            get {
                return this.imgEstadoField;
            }
            set {
                this.imgEstadoField = value;
                this.RaisePropertyChanged("ImgEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado {
            get {
                return this.nombreEstadoField;
            }
            set {
                this.nombreEstadoField = value;
                this.RaisePropertyChanged("NombreEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
                this.RaisePropertyChanged("Estacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdCodigo {
            get {
                return this.idCodigoField;
            }
            set {
                this.idCodigoField = value;
                this.RaisePropertyChanged("IdCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
                this.RaisePropertyChanged("ambiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VisitasSoapChannel : SIMANET_W22R.srvGestionSeguridadPlanta.VisitasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VisitasSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionSeguridadPlanta.VisitasSoap>, SIMANET_W22R.srvGestionSeguridadPlanta.VisitasSoap {
        
        public VisitasSoapClient() {
        }
        
        public VisitasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VisitasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VisitasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ListarTodos(string S_PROGRAMACION, string S_PERIODO, string S_TIPOPROGRA, string UserName) {
            return base.Channel.ListarTodos(S_PROGRAMACION, S_PERIODO, S_TIPOPROGRA, UserName);
        }
        
        public System.Threading.Tasks.Task<string> ListarTodosAsync(string S_PROGRAMACION, string S_PERIODO, string S_TIPOPROGRA, string UserName) {
            return base.Channel.ListarTodosAsync(S_PROGRAMACION, S_PERIODO, S_TIPOPROGRA, UserName);
        }
        
        public string ListarProgramacionVisita_JSON(string Id1, string Id2, string Id3, string UserName) {
            return base.Channel.ListarProgramacionVisita_JSON(Id1, Id2, Id3, UserName);
        }
        
        public System.Threading.Tasks.Task<string> ListarProgramacionVisita_JSONAsync(string Id1, string Id2, string Id3, string UserName) {
            return base.Channel.ListarProgramacionVisita_JSONAsync(Id1, Id2, Id3, UserName);
        }
        
        public string ProgramacionVisita_Ins(string IdTipoVisita, string IdEntidad, string IdArea, string FechaInicio, string FechaTermino, string HoraInicio, string HoraTermino, string IdCIASeguros, string NroPoliza, string Observaciones, string IdUsuarioRegistro, string TipoProgramacion, string IdUsuarioAprobacion, string IdEstado, string UserName) {
            return base.Channel.ProgramacionVisita_Ins(IdTipoVisita, IdEntidad, IdArea, FechaInicio, FechaTermino, HoraInicio, HoraTermino, IdCIASeguros, NroPoliza, Observaciones, IdUsuarioRegistro, TipoProgramacion, IdUsuarioAprobacion, IdEstado, UserName);
        }
        
        public System.Threading.Tasks.Task<string> ProgramacionVisita_InsAsync(string IdTipoVisita, string IdEntidad, string IdArea, string FechaInicio, string FechaTermino, string HoraInicio, string HoraTermino, string IdCIASeguros, string NroPoliza, string Observaciones, string IdUsuarioRegistro, string TipoProgramacion, string IdUsuarioAprobacion, string IdEstado, string UserName) {
            return base.Channel.ProgramacionVisita_InsAsync(IdTipoVisita, IdEntidad, IdArea, FechaInicio, FechaTermino, HoraInicio, HoraTermino, IdCIASeguros, NroPoliza, Observaciones, IdUsuarioRegistro, TipoProgramacion, IdUsuarioAprobacion, IdEstado, UserName);
        }
        
        public string ProgramacionVisitas_Ins(SIMANET_W22R.srvGestionSeguridadPlanta.ProgramacionBE oProgramacionBE, string LstCorreos, string LstAnexos) {
            return base.Channel.ProgramacionVisitas_Ins(oProgramacionBE, LstCorreos, LstAnexos);
        }
        
        public System.Threading.Tasks.Task<string> ProgramacionVisitas_InsAsync(SIMANET_W22R.srvGestionSeguridadPlanta.ProgramacionBE oProgramacionBE, string LstCorreos, string LstAnexos) {
            return base.Channel.ProgramacionVisitas_InsAsync(oProgramacionBE, LstCorreos, LstAnexos);
        }
    }
}
