//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionPersonal {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionPersonal.PersonalSoap")]
    public interface PersonalSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarPersona(string TextFind, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarPersonaAsync(string TextFind, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarPersonal(string ApellidosYnombres, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarPersonalAsync(string ApellidosYnombres, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTrabajadorContratista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarTrabajadorContratista(string TextFind, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarTrabajadorContratista", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarTrabajadorContratistaAsync(string TextFind, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePersonaUbicacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE DetallePersonaUbicacion(int IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePersonaUbicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE> DetallePersonaUbicacionAsync(int IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePersonaO7xCodigo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE DetallePersonaO7xCodigo(int IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePersonaO7xCodigo", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE> DetallePersonaO7xCodigoAsync(int IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeeHuallaRelogInsertaInBD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        string LeeHuallaRelogInsertaInBD(string CodTrabajador, string IdHuella, string HuellaM1, string HuellaM2, int Version, int IdOrg, int IdEstado, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeeHuallaRelogInsertaInBD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LeeHuallaRelogInsertaInBDAsync(string CodTrabajador, string IdHuella, string HuellaM1, string HuellaM2, int Version, int IdOrg, int IdEstado, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosFijosActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        void DatosFijosActualizar(
                    int Ano_prc, 
                    int Cod_emp, 
                    string Cod_itm, 
                    string Dv_rol, 
                    int Mes_prc, 
                    double Mnt_itm, 
                    string Nivel_fun, 
                    int Rol, 
                    string Tip_itm, 
                    string Mon_itm, 
                    int Ano_ini_vig, 
                    int Mes_ini_vig, 
                    int Ano_trm_vig, 
                    int Mes_trm_vig, 
                    string Cc, 
                    string Mon_alt_itm, 
                    int Nro_cuo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosFijosActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task DatosFijosActualizarAsync(
                    int Ano_prc, 
                    int Cod_emp, 
                    string Cod_itm, 
                    string Dv_rol, 
                    int Mes_prc, 
                    double Mnt_itm, 
                    string Nivel_fun, 
                    int Rol, 
                    string Tip_itm, 
                    string Mon_itm, 
                    int Ano_ini_vig, 
                    int Mes_ini_vig, 
                    int Ano_trm_vig, 
                    int Mes_trm_vig, 
                    string Cc, 
                    string Mon_alt_itm, 
                    int Nro_cuo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atributos_Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        void Atributos_Actualizar(int Cod_emp, int Rol, string Tipo, int Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Atributos_Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task Atributos_ActualizarAsync(int Cod_emp, int Rol, string Tipo, int Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Vacaciones_Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        void Vacaciones_Agregar(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Vacaciones_Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task Vacaciones_AgregarAsync(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Vacaciones_Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        void Vacaciones_Eliminar(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Vacaciones_Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task Vacaciones_EliminarAsync(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonalUbicacionBE : BaseBE {
        
        private int idPersonalField;
        
        private string nroPersonalField;
        
        private string docIdentidadField;
        
        private string apellidosyNombresField;
        
        private string nombreAreaField;
        
        private string eMailField;
        
        private string codigoAreaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPersonal {
            get {
                return this.idPersonalField;
            }
            set {
                this.idPersonalField = value;
                this.RaisePropertyChanged("IdPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NroPersonal {
            get {
                return this.nroPersonalField;
            }
            set {
                this.nroPersonalField = value;
                this.RaisePropertyChanged("NroPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocIdentidad {
            get {
                return this.docIdentidadField;
            }
            set {
                this.docIdentidadField = value;
                this.RaisePropertyChanged("DocIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApellidosyNombres {
            get {
                return this.apellidosyNombresField;
            }
            set {
                this.apellidosyNombresField = value;
                this.RaisePropertyChanged("ApellidosyNombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreArea {
            get {
                return this.nombreAreaField;
            }
            set {
                this.nombreAreaField = value;
                this.RaisePropertyChanged("NombreArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CodigoArea {
            get {
                return this.codigoAreaField;
            }
            set {
                this.codigoAreaField = value;
                this.RaisePropertyChanged("CodigoArea");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonalUbicacionBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string sucursalField;
        
        private string estacionField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        private System.DateTime fechaField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado {
            get {
                return this.imgEstadoField;
            }
            set {
                this.imgEstadoField = value;
                this.RaisePropertyChanged("ImgEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado {
            get {
                return this.nombreEstadoField;
            }
            set {
                this.nombreEstadoField = value;
                this.RaisePropertyChanged("NombreEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
                this.RaisePropertyChanged("Estacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdCodigo {
            get {
                return this.idCodigoField;
            }
            set {
                this.idCodigoField = value;
                this.RaisePropertyChanged("IdCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
                this.RaisePropertyChanged("ambiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonalSoapChannel : SIMANET_W22R.srvGestionPersonal.PersonalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonalSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionPersonal.PersonalSoap>, SIMANET_W22R.srvGestionPersonal.PersonalSoap {
        
        public PersonalSoapClient() {
        }
        
        public PersonalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable BuscarPersona(string TextFind, string UserName) {
            return base.Channel.BuscarPersona(TextFind, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarPersonaAsync(string TextFind, string UserName) {
            return base.Channel.BuscarPersonaAsync(TextFind, UserName);
        }
        
        public System.Data.DataTable BuscarPersonal(string ApellidosYnombres, string UserName) {
            return base.Channel.BuscarPersonal(ApellidosYnombres, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarPersonalAsync(string ApellidosYnombres, string UserName) {
            return base.Channel.BuscarPersonalAsync(ApellidosYnombres, UserName);
        }
        
        public System.Data.DataTable BuscarTrabajadorContratista(string TextFind, string UserName) {
            return base.Channel.BuscarTrabajadorContratista(TextFind, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarTrabajadorContratistaAsync(string TextFind, string UserName) {
            return base.Channel.BuscarTrabajadorContratistaAsync(TextFind, UserName);
        }
        
        public SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE DetallePersonaUbicacion(int IdPersonal, string UserName) {
            return base.Channel.DetallePersonaUbicacion(IdPersonal, UserName);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE> DetallePersonaUbicacionAsync(int IdPersonal, string UserName) {
            return base.Channel.DetallePersonaUbicacionAsync(IdPersonal, UserName);
        }
        
        public SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE DetallePersonaO7xCodigo(int IdPersonal, string UserName) {
            return base.Channel.DetallePersonaO7xCodigo(IdPersonal, UserName);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionPersonal.PersonalUbicacionBE> DetallePersonaO7xCodigoAsync(int IdPersonal, string UserName) {
            return base.Channel.DetallePersonaO7xCodigoAsync(IdPersonal, UserName);
        }
        
        public string LeeHuallaRelogInsertaInBD(string CodTrabajador, string IdHuella, string HuellaM1, string HuellaM2, int Version, int IdOrg, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.LeeHuallaRelogInsertaInBD(CodTrabajador, IdHuella, HuellaM1, HuellaM2, Version, IdOrg, IdEstado, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<string> LeeHuallaRelogInsertaInBDAsync(string CodTrabajador, string IdHuella, string HuellaM1, string HuellaM2, int Version, int IdOrg, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.LeeHuallaRelogInsertaInBDAsync(CodTrabajador, IdHuella, HuellaM1, HuellaM2, Version, IdOrg, IdEstado, IdUsuario, UserName);
        }
        
        public void DatosFijosActualizar(
                    int Ano_prc, 
                    int Cod_emp, 
                    string Cod_itm, 
                    string Dv_rol, 
                    int Mes_prc, 
                    double Mnt_itm, 
                    string Nivel_fun, 
                    int Rol, 
                    string Tip_itm, 
                    string Mon_itm, 
                    int Ano_ini_vig, 
                    int Mes_ini_vig, 
                    int Ano_trm_vig, 
                    int Mes_trm_vig, 
                    string Cc, 
                    string Mon_alt_itm, 
                    int Nro_cuo) {
            base.Channel.DatosFijosActualizar(Ano_prc, Cod_emp, Cod_itm, Dv_rol, Mes_prc, Mnt_itm, Nivel_fun, Rol, Tip_itm, Mon_itm, Ano_ini_vig, Mes_ini_vig, Ano_trm_vig, Mes_trm_vig, Cc, Mon_alt_itm, Nro_cuo);
        }
        
        public System.Threading.Tasks.Task DatosFijosActualizarAsync(
                    int Ano_prc, 
                    int Cod_emp, 
                    string Cod_itm, 
                    string Dv_rol, 
                    int Mes_prc, 
                    double Mnt_itm, 
                    string Nivel_fun, 
                    int Rol, 
                    string Tip_itm, 
                    string Mon_itm, 
                    int Ano_ini_vig, 
                    int Mes_ini_vig, 
                    int Ano_trm_vig, 
                    int Mes_trm_vig, 
                    string Cc, 
                    string Mon_alt_itm, 
                    int Nro_cuo) {
            return base.Channel.DatosFijosActualizarAsync(Ano_prc, Cod_emp, Cod_itm, Dv_rol, Mes_prc, Mnt_itm, Nivel_fun, Rol, Tip_itm, Mon_itm, Ano_ini_vig, Mes_ini_vig, Ano_trm_vig, Mes_trm_vig, Cc, Mon_alt_itm, Nro_cuo);
        }
        
        public void Atributos_Actualizar(int Cod_emp, int Rol, string Tipo, int Valor) {
            base.Channel.Atributos_Actualizar(Cod_emp, Rol, Tipo, Valor);
        }
        
        public System.Threading.Tasks.Task Atributos_ActualizarAsync(int Cod_emp, int Rol, string Tipo, int Valor) {
            return base.Channel.Atributos_ActualizarAsync(Cod_emp, Rol, Tipo, Valor);
        }
        
        public void Vacaciones_Agregar(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini) {
            base.Channel.Vacaciones_Agregar(Rol, Per_vac, Mes_ter, Mes_ini, Dv_rol, Dia_ter, Dia_tdo, Dia_ini, Cod_emp, Ano_ter, Ano_ini);
        }
        
        public System.Threading.Tasks.Task Vacaciones_AgregarAsync(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini) {
            return base.Channel.Vacaciones_AgregarAsync(Rol, Per_vac, Mes_ter, Mes_ini, Dv_rol, Dia_ter, Dia_tdo, Dia_ini, Cod_emp, Ano_ter, Ano_ini);
        }
        
        public void Vacaciones_Eliminar(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini) {
            base.Channel.Vacaciones_Eliminar(Rol, Per_vac, Mes_ter, Mes_ini, Dv_rol, Dia_ter, Dia_tdo, Dia_ini, Cod_emp, Ano_ter, Ano_ini);
        }
        
        public System.Threading.Tasks.Task Vacaciones_EliminarAsync(int Rol, int Per_vac, int Mes_ter, int Mes_ini, string Dv_rol, int Dia_ter, double Dia_tdo, int Dia_ini, int Cod_emp, int Ano_ter, int Ano_ini) {
            return base.Channel.Vacaciones_EliminarAsync(Rol, Per_vac, Mes_ter, Mes_ini, Dv_rol, Dia_ter, Dia_tdo, Dia_ini, Cod_emp, Ano_ter, Ano_ini);
        }
    }
}
