//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionProd_Mantenimiento {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionProd_Mantenimiento.MantenimientoSoap")]
    public interface MantenimientoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_gasto_otx_fecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_gasto_otx_fecha(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_gasto_otx_fecha", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_gasto_otx_fechaAsync(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_gasto_otx_fecha2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_gasto_otx_fecha2(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_gasto_otx_fecha2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_gasto_otx_fecha2Async(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ots_se", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_ots_se(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ots_se", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_ots_seAsync(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ots_se2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_ots_se2(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ots_se2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_ots_se2Async(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ots_se_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_ots_se_v2(string v_CO, string v_DIVISION, string N_OT, string D_Fecha_Inicio, string D_Fecha_Termino, string v_BIEN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ots_se_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_ots_se_v2Async(string v_CO, string v_DIVISION, string N_OT, string D_Fecha_Inicio, string D_Fecha_Termino, string v_BIEN, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_consumo_mat_ots", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_consumo_mat_ots(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_consumo_mat_ots", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_consumo_mat_otsAsync(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_consumo_mat_ots2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_consumo_mat_ots2(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_consumo_mat_ots2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_consumo_mat_ots2Async(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_recursos_ots", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_recursos_ots(string V_Anio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_recursos_ots", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_recursos_otsAsync(string V_Anio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_recursos_ots2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Listar_recursos_ots2(string V_Anio, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_recursos_ots2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Listar_recursos_ots2Async(string V_Anio, string UserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MantenimientoSoapChannel : SIMANET_W22R.srvGestionProd_Mantenimiento.MantenimientoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MantenimientoSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionProd_Mantenimiento.MantenimientoSoap>, SIMANET_W22R.srvGestionProd_Mantenimiento.MantenimientoSoap {
        
        public MantenimientoSoapClient() {
        }
        
        public MantenimientoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MantenimientoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Listar_gasto_otx_fecha(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_gasto_otx_fecha(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_gasto_otx_fechaAsync(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_gasto_otx_fechaAsync(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public string Listar_gasto_otx_fecha2(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_gasto_otx_fecha2(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_gasto_otx_fecha2Async(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_gasto_otx_fecha2Async(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public System.Data.DataTable Listar_ots_se(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName) {
            return base.Channel.Listar_ots_se(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, V_BIEN, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_ots_seAsync(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName) {
            return base.Channel.Listar_ots_seAsync(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, V_BIEN, UserName);
        }
        
        public string Listar_ots_se2(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName) {
            return base.Channel.Listar_ots_se2(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, V_BIEN, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_ots_se2Async(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string V_BIEN, string UserName) {
            return base.Channel.Listar_ots_se2Async(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, V_BIEN, UserName);
        }
        
        public string Listar_ots_se_v2(string v_CO, string v_DIVISION, string N_OT, string D_Fecha_Inicio, string D_Fecha_Termino, string v_BIEN, string UserName) {
            return base.Channel.Listar_ots_se_v2(v_CO, v_DIVISION, N_OT, D_Fecha_Inicio, D_Fecha_Termino, v_BIEN, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_ots_se_v2Async(string v_CO, string v_DIVISION, string N_OT, string D_Fecha_Inicio, string D_Fecha_Termino, string v_BIEN, string UserName) {
            return base.Channel.Listar_ots_se_v2Async(v_CO, v_DIVISION, N_OT, D_Fecha_Inicio, D_Fecha_Termino, v_BIEN, UserName);
        }
        
        public System.Data.DataTable Listar_consumo_mat_ots(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_consumo_mat_ots(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_consumo_mat_otsAsync(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_consumo_mat_otsAsync(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public string Listar_consumo_mat_ots2(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_consumo_mat_ots2(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_consumo_mat_ots2Async(string V_CEO, string V_CODDIV, string V_OT, string V_FINICIO, string V_FTERMINO, string UserName) {
            return base.Channel.Listar_consumo_mat_ots2Async(V_CEO, V_CODDIV, V_OT, V_FINICIO, V_FTERMINO, UserName);
        }
        
        public System.Data.DataTable Listar_recursos_ots(string V_Anio, string UserName) {
            return base.Channel.Listar_recursos_ots(V_Anio, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_recursos_otsAsync(string V_Anio, string UserName) {
            return base.Channel.Listar_recursos_otsAsync(V_Anio, UserName);
        }
        
        public string Listar_recursos_ots2(string V_Anio, string UserName) {
            return base.Channel.Listar_recursos_ots2(V_Anio, UserName);
        }
        
        public System.Threading.Tasks.Task<string> Listar_recursos_ots2Async(string V_Anio, string UserName) {
            return base.Channel.Listar_recursos_ots2Async(V_Anio, UserName);
        }
    }
}
