//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionTesoreria {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionTesoreria.TesoreriaSoap")]
    public interface TesoreriaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conci_banc_r_cartola_conc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_conci_banc_r_cartola_conc(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conci_banc_r_cartola_conc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_conci_banc_r_cartola_concAsync(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conci_bancaria_res_cartol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_conci_bancaria_res_cartol(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conci_bancaria_res_cartol", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_conci_bancaria_res_cartolAsync(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conciliacion_banc_cartola", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_conciliacion_banc_cartola(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_conciliacion_banc_cartola", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_conciliacion_banc_cartolaAsync(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_detalle_ffj_gf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_detalle_ffj_gf(string D_AÑO, string V_LIQUIDACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_detalle_ffj_gf", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_detalle_ffj_gfAsync(string D_AÑO, string V_LIQUIDACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_libro_banco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_libro_banco(string D_AÑO, string D_MES, string V_BANCO, string V_CENTRO_OPERATIVO, string V_CUENTA_CORRIENTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_libro_banco", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_libro_bancoAsync(string D_AÑO, string D_MES, string V_BANCO, string V_CENTRO_OPERATIVO, string V_CUENTA_CORRIENTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_res_ffj_x_centro_costos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_res_ffj_x_centro_costos(string D_AÑO, string V_LIQUIDACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_res_ffj_x_centro_costos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_res_ffj_x_centro_costosAsync(string D_AÑO, string V_LIQUIDACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_egresos_directos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_cheques_egresos_directos(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_MONEDA, string V_TIPO_DE_OPERACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_egresos_directos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_egresos_directosAsync(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_MONEDA, string V_TIPO_DE_OPERACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Estado_Cuenta_Doc_Elect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Estado_Cuenta_Doc_Elect(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Estado_Cuenta_Doc_Elect", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Estado_Cuenta_Doc_ElectAsync(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Estado_de_Cuenta_por_Doc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Estado_de_Cuenta_por_Doc(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Estado_de_Cuenta_por_Doc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Estado_de_Cuenta_por_DocAsync(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_folios_pendientes_o7", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_folios_pendientes_o7(string D_AÑO, string D_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_folios_pendientes_o7", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_folios_pendientes_o7Async(string D_AÑO, string D_MES, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ingresos_contabilizados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_ingresos_contabilizados(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_DESDE, string V_EMPRESA_DESDE, string V_EMPRESA_HASTA, string V_HASTA, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ingresos_contabilizados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_ingresos_contabilizadosAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_DESDE, string V_EMPRESA_DESDE, string V_EMPRESA_HASTA, string V_HASTA, string V_MONEDA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ventas_x_orden_trabajo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_ventas_x_orden_trabajo(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_ventas_x_orden_trabajo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_ventas_x_orden_trabajoAsync(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_cobrar_sector_privado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_fact_cobrar_sector_privado(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_cobrar_sector_privado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_cobrar_sector_privadoAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_cobrar_sector_marina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_fact_cobrar_sector_marina(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_cobrar_sector_marina", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_cobrar_sector_marinaAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Parte_de_Cobranzas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Parte_de_Cobranzas(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Parte_de_Cobranzas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Parte_de_CobranzasAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Documentos_por_Cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Documentos_por_Cliente(string V_Centro_Operativo, string V_Cliente, string D_Año_Desde, string D_Año_Hasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Documentos_por_Cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Documentos_por_ClienteAsync(string V_Centro_Operativo, string V_Cliente, string D_Año_Desde, string D_Año_Hasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Fact_Men_X_Linea_Neg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Fact_Men_X_Linea_Neg(string V_Centro_Operativo, string D_Año, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Fact_Men_X_Linea_Neg", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Fact_Men_X_Linea_NegAsync(string V_Centro_Operativo, string D_Año, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Orden_Trabajo_Datos_Gener", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Orden_Trabajo_Datos_Gener(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Orden_Trabajo_Datos_Gener", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Orden_Trabajo_Datos_GenerAsync(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Anexo_Diques", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_Anexo_Diques(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_Anexo_Diques", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_Anexo_DiquesAsync(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheque_giradoxnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_cheque_giradoxnum(string V_CENTRO_OPERATIVO, string V_CHEQUE_NUMERO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheque_giradoxnum", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheque_giradoxnumAsync(string V_CENTRO_OPERATIVO, string V_CHEQUE_NUMERO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_emitidos_resumen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_cheques_emitidos_resumen(string D_AÑO, string V_CENTRO_OPERATIVO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_emitidos_resumen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_emitidos_resumenAsync(string D_AÑO, string V_CENTRO_OPERATIVO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_giradosxprove_det", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_cheques_giradosxprove_det(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_giradosxprove_det", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_giradosxprove_detAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_giradosxprove_res", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_cheques_giradosxprove_res(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_giradosxprove_res", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_giradosxprove_resAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_por_observacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_cheques_por_observacion(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_OBSERVACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_cheques_por_observacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_por_observacionAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_OBSERVACION, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_lote_de_detrac_por_doc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_lote_de_detrac_por_doc(string V_CENTRO_OPERATIVO, string V_NUMERO_DE_LOTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_lote_de_detrac_por_doc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_lote_de_detrac_por_docAsync(string V_CENTRO_OPERATIVO, string V_NUMERO_DE_LOTE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_pagar_pendientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_fact_pagar_pendientes(string V_RECURSO, string V_RUC, string V_PROYECTO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_pagar_pendientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_pagar_pendientesAsync(string V_RECURSO, string V_RUC, string V_PROYECTO, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_por_pagar_doc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_fact_por_pagar_doc(string D_AÑO, string D_MES, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_fact_por_pagar_doc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_por_pagar_docAsync(string D_AÑO, string D_MES, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_facturas_por_pagar_total", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_facturas_por_pagar_total(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_facturas_por_pagar_total", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_facturas_por_pagar_totalAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_pago_proveedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_pago_proveedores(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_pago_proveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_pago_proveedoresAsync(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_pago_Facturas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar_pago_Facturas(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar_pago_Facturas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Listar_pago_FacturasAsync(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaLineas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListaLineas(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaLineas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaLineasAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaProyectosSinDep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListaProyectosSinDep(string V_NOMBRE, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaProyectosSinDep", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaProyectosSinDepAsync(string V_NOMBRE, string UserName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesoreriaSoapChannel : SIMANET_W22R.srvGestionTesoreria.TesoreriaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesoreriaSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionTesoreria.TesoreriaSoap>, SIMANET_W22R.srvGestionTesoreria.TesoreriaSoap {
        
        public TesoreriaSoapClient() {
        }
        
        public TesoreriaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TesoreriaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesoreriaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesoreriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Listar_conci_banc_r_cartola_conc(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName) {
            return base.Channel.Listar_conci_banc_r_cartola_conc(D_AÑO, D_MES, V_CARTOLA, V_CENTRO_OPERATIVO, V_MONEDA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_conci_banc_r_cartola_concAsync(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName) {
            return base.Channel.Listar_conci_banc_r_cartola_concAsync(D_AÑO, D_MES, V_CARTOLA, V_CENTRO_OPERATIVO, V_MONEDA, UserName);
        }
        
        public System.Data.DataTable Listar_conci_bancaria_res_cartol(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName) {
            return base.Channel.Listar_conci_bancaria_res_cartol(D_AÑO, D_MES, V_CARTOLA, V_CENTRO_OPERATIVO, V_MONEDA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_conci_bancaria_res_cartolAsync(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName) {
            return base.Channel.Listar_conci_bancaria_res_cartolAsync(D_AÑO, D_MES, V_CARTOLA, V_CENTRO_OPERATIVO, V_MONEDA, UserName);
        }
        
        public System.Data.DataTable Listar_conciliacion_banc_cartola(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName) {
            return base.Channel.Listar_conciliacion_banc_cartola(D_AÑO, D_MES, V_CARTOLA, V_CENTRO_OPERATIVO, V_MONEDA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_conciliacion_banc_cartolaAsync(string D_AÑO, string D_MES, string V_CARTOLA, string V_CENTRO_OPERATIVO, string V_MONEDA, string UserName) {
            return base.Channel.Listar_conciliacion_banc_cartolaAsync(D_AÑO, D_MES, V_CARTOLA, V_CENTRO_OPERATIVO, V_MONEDA, UserName);
        }
        
        public System.Data.DataTable Listar_detalle_ffj_gf(string D_AÑO, string V_LIQUIDACION, string UserName) {
            return base.Channel.Listar_detalle_ffj_gf(D_AÑO, V_LIQUIDACION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_detalle_ffj_gfAsync(string D_AÑO, string V_LIQUIDACION, string UserName) {
            return base.Channel.Listar_detalle_ffj_gfAsync(D_AÑO, V_LIQUIDACION, UserName);
        }
        
        public System.Data.DataTable Listar_libro_banco(string D_AÑO, string D_MES, string V_BANCO, string V_CENTRO_OPERATIVO, string V_CUENTA_CORRIENTE, string UserName) {
            return base.Channel.Listar_libro_banco(D_AÑO, D_MES, V_BANCO, V_CENTRO_OPERATIVO, V_CUENTA_CORRIENTE, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_libro_bancoAsync(string D_AÑO, string D_MES, string V_BANCO, string V_CENTRO_OPERATIVO, string V_CUENTA_CORRIENTE, string UserName) {
            return base.Channel.Listar_libro_bancoAsync(D_AÑO, D_MES, V_BANCO, V_CENTRO_OPERATIVO, V_CUENTA_CORRIENTE, UserName);
        }
        
        public System.Data.DataTable Listar_res_ffj_x_centro_costos(string D_AÑO, string V_LIQUIDACION, string UserName) {
            return base.Channel.Listar_res_ffj_x_centro_costos(D_AÑO, V_LIQUIDACION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_res_ffj_x_centro_costosAsync(string D_AÑO, string V_LIQUIDACION, string UserName) {
            return base.Channel.Listar_res_ffj_x_centro_costosAsync(D_AÑO, V_LIQUIDACION, UserName);
        }
        
        public System.Data.DataTable Listar_cheques_egresos_directos(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_MONEDA, string V_TIPO_DE_OPERACION, string UserName) {
            return base.Channel.Listar_cheques_egresos_directos(D_AÑO, D_MES_DESDE, D_MES_HASTA, V_CENTRO_OPERATIVO, V_MONEDA, V_TIPO_DE_OPERACION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_egresos_directosAsync(string D_AÑO, string D_MES_DESDE, string D_MES_HASTA, string V_CENTRO_OPERATIVO, string V_MONEDA, string V_TIPO_DE_OPERACION, string UserName) {
            return base.Channel.Listar_cheques_egresos_directosAsync(D_AÑO, D_MES_DESDE, D_MES_HASTA, V_CENTRO_OPERATIVO, V_MONEDA, V_TIPO_DE_OPERACION, UserName);
        }
        
        public System.Data.DataTable Listar_Estado_Cuenta_Doc_Elect(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName) {
            return base.Channel.Listar_Estado_Cuenta_Doc_Elect(V_Centro_Operativo, V_Documento, V_Nro_de_Serie, V_Nro_Correlativo, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Estado_Cuenta_Doc_ElectAsync(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName) {
            return base.Channel.Listar_Estado_Cuenta_Doc_ElectAsync(V_Centro_Operativo, V_Documento, V_Nro_de_Serie, V_Nro_Correlativo, UserName);
        }
        
        public System.Data.DataTable Listar_Estado_de_Cuenta_por_Doc(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName) {
            return base.Channel.Listar_Estado_de_Cuenta_por_Doc(V_Centro_Operativo, V_Documento, V_Nro_de_Serie, V_Nro_Correlativo, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Estado_de_Cuenta_por_DocAsync(string V_Centro_Operativo, string V_Documento, string V_Nro_de_Serie, string V_Nro_Correlativo, string UserName) {
            return base.Channel.Listar_Estado_de_Cuenta_por_DocAsync(V_Centro_Operativo, V_Documento, V_Nro_de_Serie, V_Nro_Correlativo, UserName);
        }
        
        public System.Data.DataTable Listar_folios_pendientes_o7(string D_AÑO, string D_MES, string UserName) {
            return base.Channel.Listar_folios_pendientes_o7(D_AÑO, D_MES, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_folios_pendientes_o7Async(string D_AÑO, string D_MES, string UserName) {
            return base.Channel.Listar_folios_pendientes_o7Async(D_AÑO, D_MES, UserName);
        }
        
        public System.Data.DataTable Listar_ingresos_contabilizados(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_DESDE, string V_EMPRESA_DESDE, string V_EMPRESA_HASTA, string V_HASTA, string V_MONEDA, string UserName) {
            return base.Channel.Listar_ingresos_contabilizados(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CONCEPTO, V_DESDE, V_EMPRESA_DESDE, V_EMPRESA_HASTA, V_HASTA, V_MONEDA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_ingresos_contabilizadosAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_CONCEPTO, string V_DESDE, string V_EMPRESA_DESDE, string V_EMPRESA_HASTA, string V_HASTA, string V_MONEDA, string UserName) {
            return base.Channel.Listar_ingresos_contabilizadosAsync(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_CONCEPTO, V_DESDE, V_EMPRESA_DESDE, V_EMPRESA_HASTA, V_HASTA, V_MONEDA, UserName);
        }
        
        public System.Data.DataTable Listar_ventas_x_orden_trabajo(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName) {
            return base.Channel.Listar_ventas_x_orden_trabajo(V_CENTRO_OPERATIVO, V_DIVISION, V_NUMERO_OT, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_ventas_x_orden_trabajoAsync(string V_CENTRO_OPERATIVO, string V_DIVISION, string V_NUMERO_OT, string UserName) {
            return base.Channel.Listar_ventas_x_orden_trabajoAsync(V_CENTRO_OPERATIVO, V_DIVISION, V_NUMERO_OT, UserName);
        }
        
        public System.Data.DataTable Listar_fact_cobrar_sector_privado(string UserName) {
            return base.Channel.Listar_fact_cobrar_sector_privado(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_cobrar_sector_privadoAsync(string UserName) {
            return base.Channel.Listar_fact_cobrar_sector_privadoAsync(UserName);
        }
        
        public System.Data.DataTable Listar_fact_cobrar_sector_marina(string UserName) {
            return base.Channel.Listar_fact_cobrar_sector_marina(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_cobrar_sector_marinaAsync(string UserName) {
            return base.Channel.Listar_fact_cobrar_sector_marinaAsync(UserName);
        }
        
        public System.Data.DataTable Listar_Parte_de_Cobranzas(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Parte_de_Cobranzas(V_Centro_Operativo, D_Año, D_Mes, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Parte_de_CobranzasAsync(string V_Centro_Operativo, string D_Año, string D_Mes, string UserName) {
            return base.Channel.Listar_Parte_de_CobranzasAsync(V_Centro_Operativo, D_Año, D_Mes, UserName);
        }
        
        public System.Data.DataTable Listar_Documentos_por_Cliente(string V_Centro_Operativo, string V_Cliente, string D_Año_Desde, string D_Año_Hasta, string UserName) {
            return base.Channel.Listar_Documentos_por_Cliente(V_Centro_Operativo, V_Cliente, D_Año_Desde, D_Año_Hasta, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Documentos_por_ClienteAsync(string V_Centro_Operativo, string V_Cliente, string D_Año_Desde, string D_Año_Hasta, string UserName) {
            return base.Channel.Listar_Documentos_por_ClienteAsync(V_Centro_Operativo, V_Cliente, D_Año_Desde, D_Año_Hasta, UserName);
        }
        
        public System.Data.DataTable Listar_Fact_Men_X_Linea_Neg(string V_Centro_Operativo, string D_Año, string UserName) {
            return base.Channel.Listar_Fact_Men_X_Linea_Neg(V_Centro_Operativo, D_Año, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Fact_Men_X_Linea_NegAsync(string V_Centro_Operativo, string D_Año, string UserName) {
            return base.Channel.Listar_Fact_Men_X_Linea_NegAsync(V_Centro_Operativo, D_Año, UserName);
        }
        
        public System.Data.DataTable Listar_Orden_Trabajo_Datos_Gener(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName) {
            return base.Channel.Listar_Orden_Trabajo_Datos_Gener(V_Centro_Operativo, V_Division, V_Numero_OT, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Orden_Trabajo_Datos_GenerAsync(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName) {
            return base.Channel.Listar_Orden_Trabajo_Datos_GenerAsync(V_Centro_Operativo, V_Division, V_Numero_OT, UserName);
        }
        
        public System.Data.DataTable Listar_Anexo_Diques(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName) {
            return base.Channel.Listar_Anexo_Diques(V_Centro_Operativo, V_Division, V_Numero_OT, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_Anexo_DiquesAsync(string V_Centro_Operativo, string V_Division, string V_Numero_OT, string UserName) {
            return base.Channel.Listar_Anexo_DiquesAsync(V_Centro_Operativo, V_Division, V_Numero_OT, UserName);
        }
        
        public System.Data.DataTable Listar_cheque_giradoxnum(string V_CENTRO_OPERATIVO, string V_CHEQUE_NUMERO, string UserName) {
            return base.Channel.Listar_cheque_giradoxnum(V_CENTRO_OPERATIVO, V_CHEQUE_NUMERO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheque_giradoxnumAsync(string V_CENTRO_OPERATIVO, string V_CHEQUE_NUMERO, string UserName) {
            return base.Channel.Listar_cheque_giradoxnumAsync(V_CENTRO_OPERATIVO, V_CHEQUE_NUMERO, UserName);
        }
        
        public System.Data.DataTable Listar_cheques_emitidos_resumen(string D_AÑO, string V_CENTRO_OPERATIVO, string UserName) {
            return base.Channel.Listar_cheques_emitidos_resumen(D_AÑO, V_CENTRO_OPERATIVO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_emitidos_resumenAsync(string D_AÑO, string V_CENTRO_OPERATIVO, string UserName) {
            return base.Channel.Listar_cheques_emitidos_resumenAsync(D_AÑO, V_CENTRO_OPERATIVO, UserName);
        }
        
        public System.Data.DataTable Listar_cheques_giradosxprove_det(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_cheques_giradosxprove_det(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_giradosxprove_detAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_cheques_giradosxprove_detAsync(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_cheques_giradosxprove_res(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_cheques_giradosxprove_res(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_giradosxprove_resAsync(string D_AÑO, string D_MES, string V_CENTRO_OPERATIVO, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_cheques_giradosxprove_resAsync(D_AÑO, D_MES, V_CENTRO_OPERATIVO, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_cheques_por_observacion(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_OBSERVACION, string UserName) {
            return base.Channel.Listar_cheques_por_observacion(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_OBSERVACION, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_cheques_por_observacionAsync(string D_FECHA_DESDE, string D_FECHA_HASTA, string V_CENTRO_OPERATIVO, string V_OBSERVACION, string UserName) {
            return base.Channel.Listar_cheques_por_observacionAsync(D_FECHA_DESDE, D_FECHA_HASTA, V_CENTRO_OPERATIVO, V_OBSERVACION, UserName);
        }
        
        public System.Data.DataTable Listar_lote_de_detrac_por_doc(string V_CENTRO_OPERATIVO, string V_NUMERO_DE_LOTE, string UserName) {
            return base.Channel.Listar_lote_de_detrac_por_doc(V_CENTRO_OPERATIVO, V_NUMERO_DE_LOTE, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_lote_de_detrac_por_docAsync(string V_CENTRO_OPERATIVO, string V_NUMERO_DE_LOTE, string UserName) {
            return base.Channel.Listar_lote_de_detrac_por_docAsync(V_CENTRO_OPERATIVO, V_NUMERO_DE_LOTE, UserName);
        }
        
        public System.Data.DataTable Listar_fact_pagar_pendientes(string V_RECURSO, string V_RUC, string V_PROYECTO, string UserName) {
            return base.Channel.Listar_fact_pagar_pendientes(V_RECURSO, V_RUC, V_PROYECTO, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_pagar_pendientesAsync(string V_RECURSO, string V_RUC, string V_PROYECTO, string UserName) {
            return base.Channel.Listar_fact_pagar_pendientesAsync(V_RECURSO, V_RUC, V_PROYECTO, UserName);
        }
        
        public System.Data.DataTable Listar_fact_por_pagar_doc(string D_AÑO, string D_MES, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_fact_por_pagar_doc(D_AÑO, D_MES, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_fact_por_pagar_docAsync(string D_AÑO, string D_MES, string V_RELACION_DESDE, string V_RELACION_HASTA, string UserName) {
            return base.Channel.Listar_fact_por_pagar_docAsync(D_AÑO, D_MES, V_RELACION_DESDE, V_RELACION_HASTA, UserName);
        }
        
        public System.Data.DataTable Listar_facturas_por_pagar_total(string UserName) {
            return base.Channel.Listar_facturas_por_pagar_total(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_facturas_por_pagar_totalAsync(string UserName) {
            return base.Channel.Listar_facturas_por_pagar_totalAsync(UserName);
        }
        
        public System.Data.DataTable Listar_pago_proveedores(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName) {
            return base.Channel.Listar_pago_proveedores(V_SUCURSAL, V_RUC_INI, V_RUC_FIN, v_fecha_ini, v_fecha_fin, v_operacion, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_pago_proveedoresAsync(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName) {
            return base.Channel.Listar_pago_proveedoresAsync(V_SUCURSAL, V_RUC_INI, V_RUC_FIN, v_fecha_ini, v_fecha_fin, v_operacion, UserName);
        }
        
        public System.Data.DataTable Listar_pago_Facturas(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName) {
            return base.Channel.Listar_pago_Facturas(V_SUCURSAL, V_RUC_INI, V_RUC_FIN, v_fecha_ini, v_fecha_fin, v_operacion, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Listar_pago_FacturasAsync(string V_SUCURSAL, string V_RUC_INI, string V_RUC_FIN, string v_fecha_ini, string v_fecha_fin, string v_operacion, string UserName) {
            return base.Channel.Listar_pago_FacturasAsync(V_SUCURSAL, V_RUC_INI, V_RUC_FIN, v_fecha_ini, v_fecha_fin, v_operacion, UserName);
        }
        
        public System.Data.DataTable ListaLineas(string UserName) {
            return base.Channel.ListaLineas(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaLineasAsync(string UserName) {
            return base.Channel.ListaLineasAsync(UserName);
        }
        
        public System.Data.DataTable ListaProyectosSinDep(string V_NOMBRE, string UserName) {
            return base.Channel.ListaProyectosSinDep(V_NOMBRE, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaProyectosSinDepAsync(string V_NOMBRE, string UserName) {
            return base.Channel.ListaProyectosSinDepAsync(V_NOMBRE, UserName);
        }
    }
}
