//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionReportes {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionReportes.AdministrarReportesSoap")]
    public interface AdministrarReportesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarObjetos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarObjetos(string IdPadre, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarObjetos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarObjetosAsync(string IdPadre, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarReportePorUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarReportePorUsuario(string IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarReportePorUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarReportePorUsuarioAsync(string IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarObjetosDependentes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarObjetosDependentes(string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarObjetosDependentes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarObjetosDependentesAsync(string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCtrlAttrParametro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarCtrlAttrParametro(string IdObjeto, string IdAtributoPadre, int IdTipoControl, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCtrlAttrParametro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarCtrlAttrParametroAsync(string IdObjeto, string IdAtributoPadre, int IdTipoControl, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarInformacionReporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarInformacionReporte(string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarInformacionReporte", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarInformacionReporteAsync(string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuariosxNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarUsuariosxNombre(string ApellidosyNombres, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuariosxNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuariosxNombreAsync(string ApellidosyNombres, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosCompartidoFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarUsuariosCompartidoFile(string NombreArchivo, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosCompartidoFile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosCompartidoFileAsync(string NombreArchivo, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaArchivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        string ModificaInsertaArchivo(SIMANET_W22R.srvGestionReportes.ArchivoCompartidoBE oArchivoCompartidoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaArchivo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ModificaInsertaArchivoAsync(SIMANET_W22R.srvGestionReportes.ArchivoCompartidoBE oArchivoCompartidoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaObjetoPrivilegio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        string ModificaInsertaObjetoPrivilegio(SIMANET_W22R.srvGestionReportes.ObjetoPrivilegioBE oObjetoPrivilegioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaObjetoPrivilegio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ModificaInsertaObjetoPrivilegioAsync(SIMANET_W22R.srvGestionReportes.ObjetoPrivilegioBE oObjetoPrivilegioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosxReporteCompartido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable ListarUsuariosxReporteCompartido(int IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosxReporteCompartido", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosxReporteCompartidoAsync(int IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleReporteCompartido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        SIMANET_W22R.srvGestionReportes.ObjetoReporteCompartidoBE DetalleReporteCompartido(int IdObjeto, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleReporteCompartido", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionReportes.ObjetoReporteCompartidoBE> DetalleReporteCompartidoAsync(int IdObjeto, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCabeceradeReporte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable ListarCabeceradeReporte(int IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCabeceradeReporte", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarCabeceradeReporteAsync(int IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarReportesCompartidosPorUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable ListarReportesCompartidosPorUsuario(int IdUsuario, int IdObjetoPadre, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarReportesCompartidosPorUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarReportesCompartidosPorUsuarioAsync(int IdUsuario, int IdObjetoPadre, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarObjetoAttributoValor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable ListarObjetoAttributoValor(int IdObjeto, int IdTipoControl, int IdAtributoPadre, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarObjetoAttributoValor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarObjetoAttributoValorAsync(int IdObjeto, int IdTipoControl, int IdAtributoPadre, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarObjeto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int InsertarObjeto(SIMANET_W22R.srvGestionReportes.ObjetoBE oObjetoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarObjeto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarObjetoAsync(SIMANET_W22R.srvGestionReportes.ObjetoBE oObjetoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsModObjetoConfigAtrributosValor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int InsModObjetoConfigAtrributosValor(SIMANET_W22R.srvGestionReportes.ObjetoConfigAttrBE oObjetoConfigAttrBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsModObjetoConfigAtrributosValor", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsModObjetoConfigAtrributosValorAsync(SIMANET_W22R.srvGestionReportes.ObjetoConfigAttrBE oObjetoConfigAttrBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackupParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int BackupParam(string Guid, string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackupParam", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BackupParamAsync(string Guid, string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackupConfigParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int BackupConfigParam(string Guid, string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BackupConfigParam", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BackupConfigParamAsync(string Guid, string IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MapearDatosInsertaModifica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        int MapearDatosInsertaModifica(SIMANET_W22R.srvGestionReportes.ObjetoMapeoExportBE oObjetoMapeoExportBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MapearDatosInsertaModifica", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MapearDatosInsertaModificaAsync(SIMANET_W22R.srvGestionReportes.ObjetoMapeoExportBE oObjetoMapeoExportBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MapearDatosListarTodos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable MapearDatosListarTodos(int IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MapearDatosListarTodos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> MapearDatosListarTodosAsync(int IdObjeto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteAdoptarHijo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        string ReporteAdoptarHijo(int IdObjeto, int IdPadreNuevo, int Orden, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReporteAdoptarHijo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReporteAdoptarHijoAsync(int IdObjeto, int IdPadreNuevo, int Orden, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaAccesos_RptxUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable ListaAccesos_RptxUsuario(string v_usuario, string v_ambiente, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaAccesos_RptxUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaAccesos_RptxUsuarioAsync(string v_usuario, string v_ambiente, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaAccesos_RptxUsuario_v2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBE))]
        System.Data.DataTable ListaAccesos_RptxUsuario_v2(string s_usuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaAccesos_RptxUsuario_v2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaAccesos_RptxUsuario_v2Async(string s_usuario, string UserName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArchivoCompartidoBE : BaseBE {
        
        private string idCompartidoField;
        
        private int idObjetoField;
        
        private int idUsuarioCompField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdCompartido {
            get {
                return this.idCompartidoField;
            }
            set {
                this.idCompartidoField = value;
                this.RaisePropertyChanged("IdCompartido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("IdObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdUsuarioComp {
            get {
                return this.idUsuarioCompField;
            }
            set {
                this.idUsuarioCompField = value;
                this.RaisePropertyChanged("IdUsuarioComp");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjetoMapeoExportBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjetoConfigAttrBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjetoBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjetoReporteCompartidoBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjetoPrivilegioBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchivoCompartidoBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string sucursalField;
        
        private string estacionField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        private System.DateTime fechaField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado {
            get {
                return this.imgEstadoField;
            }
            set {
                this.imgEstadoField = value;
                this.RaisePropertyChanged("ImgEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado {
            get {
                return this.nombreEstadoField;
            }
            set {
                this.nombreEstadoField = value;
                this.RaisePropertyChanged("NombreEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
                this.RaisePropertyChanged("Estacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdCodigo {
            get {
                return this.idCodigoField;
            }
            set {
                this.idCodigoField = value;
                this.RaisePropertyChanged("IdCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
                this.RaisePropertyChanged("ambiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjetoMapeoExportBE : BaseBE {
        
        private int idDataFieldField;
        
        private int idDataFieldPadreField;
        
        private string nombreField;
        
        private string aliasField;
        
        private int tipoField;
        
        private string fieldComputeField;
        
        private int exportarField;
        
        private int ordenField;
        
        private int prioridadField;
        
        private int idObjetoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdDataField {
            get {
                return this.idDataFieldField;
            }
            set {
                this.idDataFieldField = value;
                this.RaisePropertyChanged("IdDataField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdDataFieldPadre {
            get {
                return this.idDataFieldPadreField;
            }
            set {
                this.idDataFieldPadreField = value;
                this.RaisePropertyChanged("IdDataFieldPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FieldCompute {
            get {
                return this.fieldComputeField;
            }
            set {
                this.fieldComputeField = value;
                this.RaisePropertyChanged("FieldCompute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Exportar {
            get {
                return this.exportarField;
            }
            set {
                this.exportarField = value;
                this.RaisePropertyChanged("Exportar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Prioridad {
            get {
                return this.prioridadField;
            }
            set {
                this.prioridadField = value;
                this.RaisePropertyChanged("Prioridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("IdObjeto");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjetoConfigAttrBE : BaseBE {
        
        private int idAtributoValorField;
        
        private int idObjetoField;
        
        private int idAtributoField;
        
        private string valorField;
        
        private int idGrpField;
        
        private int ordenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdAtributoValor {
            get {
                return this.idAtributoValorField;
            }
            set {
                this.idAtributoValorField = value;
                this.RaisePropertyChanged("IdAtributoValor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("IdObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdAtributo {
            get {
                return this.idAtributoField;
            }
            set {
                this.idAtributoField = value;
                this.RaisePropertyChanged("IdAtributo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdGrp {
            get {
                return this.idGrpField;
            }
            set {
                this.idGrpField = value;
                this.RaisePropertyChanged("IdGrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjetoBE : BaseBE {
        
        private int idObjetoField;
        
        private int idPadreField;
        
        private string nombreField;
        
        private int idTipoField;
        
        private int idTipoControlField;
        
        private string ref1Field;
        
        private string ref2Field;
        
        private string ref3Field;
        
        private string ref4Field;
        
        private int idUsuarioAnalistaField;
        
        private int ordenXNivelField;
        
        private int idUsuarioSolicitanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("IdObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdPadre {
            get {
                return this.idPadreField;
            }
            set {
                this.idPadreField = value;
                this.RaisePropertyChanged("IdPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
                this.RaisePropertyChanged("IdTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdTipoControl {
            get {
                return this.idTipoControlField;
            }
            set {
                this.idTipoControlField = value;
                this.RaisePropertyChanged("IdTipoControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Ref1 {
            get {
                return this.ref1Field;
            }
            set {
                this.ref1Field = value;
                this.RaisePropertyChanged("Ref1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Ref2 {
            get {
                return this.ref2Field;
            }
            set {
                this.ref2Field = value;
                this.RaisePropertyChanged("Ref2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Ref3 {
            get {
                return this.ref3Field;
            }
            set {
                this.ref3Field = value;
                this.RaisePropertyChanged("Ref3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Ref4 {
            get {
                return this.ref4Field;
            }
            set {
                this.ref4Field = value;
                this.RaisePropertyChanged("Ref4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuarioAnalista {
            get {
                return this.idUsuarioAnalistaField;
            }
            set {
                this.idUsuarioAnalistaField = value;
                this.RaisePropertyChanged("IdUsuarioAnalista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int OrdenXNivel {
            get {
                return this.ordenXNivelField;
            }
            set {
                this.ordenXNivelField = value;
                this.RaisePropertyChanged("OrdenXNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int IdUsuarioSolicitante {
            get {
                return this.idUsuarioSolicitanteField;
            }
            set {
                this.idUsuarioSolicitanteField = value;
                this.RaisePropertyChanged("IdUsuarioSolicitante");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjetoReporteCompartidoBE : BaseBE {
        
        private int idPrivilegioField;
        
        private int idObjetoField;
        
        private int idUsuarioCompartidoField;
        
        private int ownerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPrivilegio {
            get {
                return this.idPrivilegioField;
            }
            set {
                this.idPrivilegioField = value;
                this.RaisePropertyChanged("IdPrivilegio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("IdObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdUsuarioCompartido {
            get {
                return this.idUsuarioCompartidoField;
            }
            set {
                this.idUsuarioCompartidoField = value;
                this.RaisePropertyChanged("IdUsuarioCompartido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjetoPrivilegioBE : BaseBE {
        
        private int idPrivilegioField;
        
        private int idObjetoField;
        
        private int idUsuarioCompartidoField;
        
        private int ownerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPrivilegio {
            get {
                return this.idPrivilegioField;
            }
            set {
                this.idPrivilegioField = value;
                this.RaisePropertyChanged("IdPrivilegio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdObjeto {
            get {
                return this.idObjetoField;
            }
            set {
                this.idObjetoField = value;
                this.RaisePropertyChanged("IdObjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdUsuarioCompartido {
            get {
                return this.idUsuarioCompartidoField;
            }
            set {
                this.idUsuarioCompartidoField = value;
                this.RaisePropertyChanged("IdUsuarioCompartido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdministrarReportesSoapChannel : SIMANET_W22R.srvGestionReportes.AdministrarReportesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministrarReportesSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionReportes.AdministrarReportesSoap>, SIMANET_W22R.srvGestionReportes.AdministrarReportesSoap {
        
        public AdministrarReportesSoapClient() {
        }
        
        public AdministrarReportesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministrarReportesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrarReportesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrarReportesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListarObjetos(string IdPadre, string UserName) {
            return base.Channel.ListarObjetos(IdPadre, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarObjetosAsync(string IdPadre, string UserName) {
            return base.Channel.ListarObjetosAsync(IdPadre, UserName);
        }
        
        public System.Data.DataTable ListarReportePorUsuario(string IdUsuario, string UserName) {
            return base.Channel.ListarReportePorUsuario(IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarReportePorUsuarioAsync(string IdUsuario, string UserName) {
            return base.Channel.ListarReportePorUsuarioAsync(IdUsuario, UserName);
        }
        
        public System.Data.DataTable ListarObjetosDependentes(string IdObjeto, string UserName) {
            return base.Channel.ListarObjetosDependentes(IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarObjetosDependentesAsync(string IdObjeto, string UserName) {
            return base.Channel.ListarObjetosDependentesAsync(IdObjeto, UserName);
        }
        
        public System.Data.DataTable ListarCtrlAttrParametro(string IdObjeto, string IdAtributoPadre, int IdTipoControl, string UserName) {
            return base.Channel.ListarCtrlAttrParametro(IdObjeto, IdAtributoPadre, IdTipoControl, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarCtrlAttrParametroAsync(string IdObjeto, string IdAtributoPadre, int IdTipoControl, string UserName) {
            return base.Channel.ListarCtrlAttrParametroAsync(IdObjeto, IdAtributoPadre, IdTipoControl, UserName);
        }
        
        public System.Data.DataTable ListarInformacionReporte(string IdObjeto, string UserName) {
            return base.Channel.ListarInformacionReporte(IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarInformacionReporteAsync(string IdObjeto, string UserName) {
            return base.Channel.ListarInformacionReporteAsync(IdObjeto, UserName);
        }
        
        public System.Data.DataTable BuscarUsuariosxNombre(string ApellidosyNombres, string UserName) {
            return base.Channel.BuscarUsuariosxNombre(ApellidosyNombres, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarUsuariosxNombreAsync(string ApellidosyNombres, string UserName) {
            return base.Channel.BuscarUsuariosxNombreAsync(ApellidosyNombres, UserName);
        }
        
        public System.Data.DataTable ListarUsuariosCompartidoFile(string NombreArchivo, string UserName) {
            return base.Channel.ListarUsuariosCompartidoFile(NombreArchivo, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosCompartidoFileAsync(string NombreArchivo, string UserName) {
            return base.Channel.ListarUsuariosCompartidoFileAsync(NombreArchivo, UserName);
        }
        
        public string ModificaInsertaArchivo(SIMANET_W22R.srvGestionReportes.ArchivoCompartidoBE oArchivoCompartidoBE) {
            return base.Channel.ModificaInsertaArchivo(oArchivoCompartidoBE);
        }
        
        public System.Threading.Tasks.Task<string> ModificaInsertaArchivoAsync(SIMANET_W22R.srvGestionReportes.ArchivoCompartidoBE oArchivoCompartidoBE) {
            return base.Channel.ModificaInsertaArchivoAsync(oArchivoCompartidoBE);
        }
        
        public string ModificaInsertaObjetoPrivilegio(SIMANET_W22R.srvGestionReportes.ObjetoPrivilegioBE oObjetoPrivilegioBE) {
            return base.Channel.ModificaInsertaObjetoPrivilegio(oObjetoPrivilegioBE);
        }
        
        public System.Threading.Tasks.Task<string> ModificaInsertaObjetoPrivilegioAsync(SIMANET_W22R.srvGestionReportes.ObjetoPrivilegioBE oObjetoPrivilegioBE) {
            return base.Channel.ModificaInsertaObjetoPrivilegioAsync(oObjetoPrivilegioBE);
        }
        
        public System.Data.DataTable ListarUsuariosxReporteCompartido(int IdObjeto, string UserName) {
            return base.Channel.ListarUsuariosxReporteCompartido(IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosxReporteCompartidoAsync(int IdObjeto, string UserName) {
            return base.Channel.ListarUsuariosxReporteCompartidoAsync(IdObjeto, UserName);
        }
        
        public SIMANET_W22R.srvGestionReportes.ObjetoReporteCompartidoBE DetalleReporteCompartido(int IdObjeto, int IdUsuario, string UserName) {
            return base.Channel.DetalleReporteCompartido(IdObjeto, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionReportes.ObjetoReporteCompartidoBE> DetalleReporteCompartidoAsync(int IdObjeto, int IdUsuario, string UserName) {
            return base.Channel.DetalleReporteCompartidoAsync(IdObjeto, IdUsuario, UserName);
        }
        
        public System.Data.DataTable ListarCabeceradeReporte(int IdObjeto, string UserName) {
            return base.Channel.ListarCabeceradeReporte(IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarCabeceradeReporteAsync(int IdObjeto, string UserName) {
            return base.Channel.ListarCabeceradeReporteAsync(IdObjeto, UserName);
        }
        
        public System.Data.DataTable ListarReportesCompartidosPorUsuario(int IdUsuario, int IdObjetoPadre, string UserName) {
            return base.Channel.ListarReportesCompartidosPorUsuario(IdUsuario, IdObjetoPadre, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarReportesCompartidosPorUsuarioAsync(int IdUsuario, int IdObjetoPadre, string UserName) {
            return base.Channel.ListarReportesCompartidosPorUsuarioAsync(IdUsuario, IdObjetoPadre, UserName);
        }
        
        public System.Data.DataTable ListarObjetoAttributoValor(int IdObjeto, int IdTipoControl, int IdAtributoPadre, string UserName) {
            return base.Channel.ListarObjetoAttributoValor(IdObjeto, IdTipoControl, IdAtributoPadre, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarObjetoAttributoValorAsync(int IdObjeto, int IdTipoControl, int IdAtributoPadre, string UserName) {
            return base.Channel.ListarObjetoAttributoValorAsync(IdObjeto, IdTipoControl, IdAtributoPadre, UserName);
        }
        
        public int InsertarObjeto(SIMANET_W22R.srvGestionReportes.ObjetoBE oObjetoBE) {
            return base.Channel.InsertarObjeto(oObjetoBE);
        }
        
        public System.Threading.Tasks.Task<int> InsertarObjetoAsync(SIMANET_W22R.srvGestionReportes.ObjetoBE oObjetoBE) {
            return base.Channel.InsertarObjetoAsync(oObjetoBE);
        }
        
        public int InsModObjetoConfigAtrributosValor(SIMANET_W22R.srvGestionReportes.ObjetoConfigAttrBE oObjetoConfigAttrBE) {
            return base.Channel.InsModObjetoConfigAtrributosValor(oObjetoConfigAttrBE);
        }
        
        public System.Threading.Tasks.Task<int> InsModObjetoConfigAtrributosValorAsync(SIMANET_W22R.srvGestionReportes.ObjetoConfigAttrBE oObjetoConfigAttrBE) {
            return base.Channel.InsModObjetoConfigAtrributosValorAsync(oObjetoConfigAttrBE);
        }
        
        public int BackupParam(string Guid, string IdObjeto, string UserName) {
            return base.Channel.BackupParam(Guid, IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<int> BackupParamAsync(string Guid, string IdObjeto, string UserName) {
            return base.Channel.BackupParamAsync(Guid, IdObjeto, UserName);
        }
        
        public int BackupConfigParam(string Guid, string IdObjeto, string UserName) {
            return base.Channel.BackupConfigParam(Guid, IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<int> BackupConfigParamAsync(string Guid, string IdObjeto, string UserName) {
            return base.Channel.BackupConfigParamAsync(Guid, IdObjeto, UserName);
        }
        
        public int MapearDatosInsertaModifica(SIMANET_W22R.srvGestionReportes.ObjetoMapeoExportBE oObjetoMapeoExportBE) {
            return base.Channel.MapearDatosInsertaModifica(oObjetoMapeoExportBE);
        }
        
        public System.Threading.Tasks.Task<int> MapearDatosInsertaModificaAsync(SIMANET_W22R.srvGestionReportes.ObjetoMapeoExportBE oObjetoMapeoExportBE) {
            return base.Channel.MapearDatosInsertaModificaAsync(oObjetoMapeoExportBE);
        }
        
        public System.Data.DataTable MapearDatosListarTodos(int IdObjeto, string UserName) {
            return base.Channel.MapearDatosListarTodos(IdObjeto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MapearDatosListarTodosAsync(int IdObjeto, string UserName) {
            return base.Channel.MapearDatosListarTodosAsync(IdObjeto, UserName);
        }
        
        public string ReporteAdoptarHijo(int IdObjeto, int IdPadreNuevo, int Orden, string UserName) {
            return base.Channel.ReporteAdoptarHijo(IdObjeto, IdPadreNuevo, Orden, UserName);
        }
        
        public System.Threading.Tasks.Task<string> ReporteAdoptarHijoAsync(int IdObjeto, int IdPadreNuevo, int Orden, string UserName) {
            return base.Channel.ReporteAdoptarHijoAsync(IdObjeto, IdPadreNuevo, Orden, UserName);
        }
        
        public System.Data.DataTable ListaAccesos_RptxUsuario(string v_usuario, string v_ambiente, string UserName) {
            return base.Channel.ListaAccesos_RptxUsuario(v_usuario, v_ambiente, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaAccesos_RptxUsuarioAsync(string v_usuario, string v_ambiente, string UserName) {
            return base.Channel.ListaAccesos_RptxUsuarioAsync(v_usuario, v_ambiente, UserName);
        }
        
        public System.Data.DataTable ListaAccesos_RptxUsuario_v2(string s_usuario, string UserName) {
            return base.Channel.ListaAccesos_RptxUsuario_v2(s_usuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaAccesos_RptxUsuario_v2Async(string s_usuario, string UserName) {
            return base.Channel.ListaAccesos_RptxUsuario_v2Async(s_usuario, UserName);
        }
    }
}
