//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMANET_W22R.srvGestionCalidad {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvGestionCalidad.ControlInspeccionesSoap")]
    public interface ControlInspeccionesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ListarInspectores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Inspeccion_ListarInspectores(string Id1, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ListarInspectores", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Inspeccion_ListarInspectoresAsync(string Id1, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarResponsablesPorArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarResponsablesPorArea(string Id1, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarResponsablesPorArea", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarResponsablesPorAreaAsync(string Id1, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ModificarInsertarInspector", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Inspeccion_ModificarInsertarInspector(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ModificarInsertarInspector", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Inspeccion_ModificarInsertarInspectorAsync(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleInspector", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIMANET_W22R.srvGestionCalidad.InspectorBE DetalleInspector(string IdInspector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleInspector", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.InspectorBE> DetalleInspectorAsync(string IdInspector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ModficarInsertarResponsable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Inspeccion_ModficarInsertarResponsable(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ModficarInsertarResponsable", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Inspeccion_ModficarInsertarResponsableAsync(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_DetalleResponsableArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIMANET_W22R.srvGestionCalidad.ResponsableAreaBE Inspeccion_DetalleResponsableArea(string IdPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_DetalleResponsableArea", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.ResponsableAreaBE> Inspeccion_DetalleResponsableAreaAsync(string IdPersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarInspeccionesxInspector", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarInspeccionesxInspector(string IdInspector, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarInspeccionesxInspector", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarInspeccionesxInspectorAsync(string IdInspector, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaModificaDetalledeInspeccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertaModificaDetalledeInspeccion(SIMANET_W22R.srvGestionCalidad.InspectorDetalleBE oInspectorDetalleBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaModificaDetalledeInspeccion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertaModificaDetalledeInspeccionAsync(SIMANET_W22R.srvGestionCalidad.InspectorDetalleBE oInspectorDetalleBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProyectosActividadSIMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarProyectosActividadSIMA(string IdProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProyectosActividadSIMA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarProyectosActividadSIMAAsync(string IdProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarActividad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarActividad(string NombreActividad, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarActividad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarActividadAsync(string NombreActividad, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAreaEntidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarAreaEntidad(string NombreAreaEntidad, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAreaEntidad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarAreaEntidadAsync(string NombreAreaEntidad, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAreaEntidad_Inspeccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarAreaEntidad_Inspeccion(string NombreAreaEntidad, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAreaEntidad_Inspeccion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarAreaEntidad_InspeccionAsync(string NombreAreaEntidad, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModficarInsertarProyectoActividadSIMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModficarInsertarProyectoActividadSIMA(SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE oProyectoActividadBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModficarInsertarProyectoActividadSIMA", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ModficarInsertarProyectoActividadSIMAAsync(SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE oProyectoActividadBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleActivadProyecto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE DetalleActivadProyecto(string IdProyecto, string IdActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetalleActivadProyecto", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE> DetalleActivadProyectoAsync(string IdProyecto, string IdActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdministrarInspeccionAnexos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AdministrarInspeccionAnexos(SIMANET_W22R.srvGestionCalidad.InspeccionAnexoBE oInspeccionAnexoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdministrarInspeccionAnexos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AdministrarInspeccionAnexosAsync(SIMANET_W22R.srvGestionCalidad.InspeccionAnexoBE oInspeccionAnexoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarInspeccionAnexos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarInspeccionAnexos(string IdInspeccion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarInspeccionAnexos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarInspeccionAnexosAsync(string IdInspeccion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosFirmantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarUsuariosFirmantes(string IdInspeccion, string IdUsuarioFirmante, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosFirmantes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosFirmantesAsync(string IdInspeccion, string IdUsuarioFirmante, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosFirmantesRefCruz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarUsuariosFirmantesRefCruz(string IdInspeccion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarUsuariosFirmantesRefCruz", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosFirmantesRefCruzAsync(string IdInspeccion, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaUsuariosFirmantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificaInsertaUsuariosFirmantes(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaUsuariosFirmantes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ModificaInsertaUsuariosFirmantesAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsModPersonalFirmantePorTipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsModPersonalFirmantePorTipo(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsModPersonalFirmantePorTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsModPersonalFirmantePorTipoAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaFirmas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ModificaInsertaFirmas(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaInsertaFirmas", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ModificaInsertaFirmasAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminaUsuariosFirmantes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int EliminaUsuariosFirmantes(string IdInspeccion, string IdUsuarioFirmante, int IdEsatdo, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminaUsuariosFirmantes", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminaUsuariosFirmantesAsync(string IdInspeccion, string IdUsuarioFirmante, int IdEsatdo, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizaNroMsgRecibidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizaNroMsgRecibidos(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizaNroMsgRecibidos", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizaNroMsgRecibidosAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirmaAprobarFromEMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int FirmaAprobarFromEMail(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FirmaAprobarFromEMail", ReplyAction="*")]
        System.Threading.Tasks.Task<int> FirmaAprobarFromEMailAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InspeccionCambiarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InspeccionCambiarEstado(string IdInspeccion, int IdEstado, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InspeccionCambiarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InspeccionCambiarEstadoAsync(string IdInspeccion, int IdEstado, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarProyectodeInspeccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarProyectodeInspeccion(string NombreProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarProyectodeInspeccion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarProyectodeInspeccionAsync(string NombreProyecto, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarDetallePorReponsabledeArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarDetallePorReponsabledeArea(string IdInspeccion, int IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarDetallePorReponsabledeArea", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarDetallePorReponsabledeAreaAsync(string IdInspeccion, int IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePorReponsabledeAreaRpt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE DetallePorReponsabledeAreaRpt(string IdDetalleResponsableArea, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePorReponsabledeAreaRpt", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE> DetallePorReponsabledeAreaRptAsync(string IdDetalleResponsableArea, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePorReponsabledeAreaCambiarEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DetallePorReponsabledeAreaCambiarEstado(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetallePorReponsabledeAreaCambiarEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DetallePorReponsabledeAreaCambiarEstadoAsync(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResponsabledeAreaDetalle_InsertaModifica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ResponsabledeAreaDetalle_InsertaModifica(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResponsabledeAreaDetalle_InsertaModifica", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ResponsabledeAreaDetalle_InsertaModificaAsync(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenInspeccionesPorEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenInspeccionesPorEstado(int Año, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenInspeccionesPorEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenInspeccionesPorEstadoAsync(int Año, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeTipoEntidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformeTipoEntidad(int Año, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeTipoEntidad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeTipoEntidadAsync(int Año, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAprobador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BuscarAprobador(string ApellidosyNombres, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAprobador", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarAprobadorAsync(string ApellidosyNombres, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BloqueaRegistroInspeccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int BloqueaRegistroInspeccion(string IdInspeccion, int Block, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BloqueaRegistroInspeccion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> BloqueaRegistroInspeccionAsync(string IdInspeccion, int Block, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Inspeccion_Listar(string Id1, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Inspeccion_ListarAsync(string Id1, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Detalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIMANET_W22R.srvGestionCalidad.InspeccionBE Inspeccion_Detalle(string Id1, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.InspeccionBE> Inspeccion_DetalleAsync(string Id1, int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ListarPorResponsableArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Inspeccion_ListarPorResponsableArea(string IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_ListarPorResponsableArea", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> Inspeccion_ListarPorResponsableAreaAsync(string IdPersonal, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Insertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Inspeccion_Insertar(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Inspeccion_InsertarAsync(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Modificar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Inspeccion_Modificar(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inspeccion_Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Inspeccion_ModificarAsync(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeIP_SIMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformeIP_SIMA(int Año, int MesHasta, int IdOrigen, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeIP_SIMA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeIP_SIMAAsync(int Año, int MesHasta, int IdOrigen, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformeIP(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeIP", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeIPAsync(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeSIMA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformeSIMA(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformeSIMA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeSIMAAsync(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformePorProyecto_Mensual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformePorProyecto_Mensual(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformePorProyecto_Mensual", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformePorProyecto_MensualAsync(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformePorIP_SIMA_Mensual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformePorIP_SIMA_Mensual(int Año, int MesHasta, int IdOrigen, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformePorIP_SIMA_Mensual", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformePorIP_SIMA_MensualAsync(int Año, int MesHasta, int IdOrigen, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformePorTipodeInspeccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ResumenNoConformePorTipodeInspeccion(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResumenNoConformePorTipodeInspeccion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformePorTipodeInspeccionAsync(int Año, int MesHasta, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarSolicitudAprobacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarSolicitudAprobacion(int IdUsuario, string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarSolicitudAprobacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarSolicitudAprobacionAsync(int IdUsuario, string UserName);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InspeccionBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponsableAreaDetalleBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UsuarioFirmanteBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InspeccionAnexoBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProyectoActividadBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InspectorDetalleBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponsableAreaBE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InspectorBE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string observacionField;
        
        private int idEstadoField;
        
        private string imgEstadoField;
        
        private string nombreEstadoField;
        
        private string sucursalField;
        
        private string estacionField;
        
        private string userNameField;
        
        private string idCodigoField;
        
        private int idUsuarioField;
        
        private string tokenField;
        
        private string ambienteField;
        
        private System.DateTime fechaField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("IdEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImgEstado {
            get {
                return this.imgEstadoField;
            }
            set {
                this.imgEstadoField = value;
                this.RaisePropertyChanged("ImgEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NombreEstado {
            get {
                return this.nombreEstadoField;
            }
            set {
                this.nombreEstadoField = value;
                this.RaisePropertyChanged("NombreEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
                this.RaisePropertyChanged("Estacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdCodigo {
            get {
                return this.idCodigoField;
            }
            set {
                this.idCodigoField = value;
                this.RaisePropertyChanged("IdCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
                this.RaisePropertyChanged("ambiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InspeccionBE : BaseBE {
        
        private string idInspeccionField;
        
        private string idInspeccionPadreField;
        
        private string nroProyectoField;
        
        private string nroReporteField;
        
        private int idProyectoField;
        
        private string nombreProyectoField;
        
        private int idCLienteField;
        
        private string clienteRazonSocialField;
        
        private System.DateTime fechaInspeccionField;
        
        private int idTipoInspeccionField;
        
        private int idTipoProcesoField;
        
        private string nombreTipoProcesoField;
        
        private int idTipoSistemaField;
        
        private int idTipoClasificacionField;
        
        private string recomendacionField;
        
        private string lineadeNegocioField;
        
        private int idNormaClausulaField;
        
        private int idOrigenField;
        
        private int idEntidadField;
        
        private string nombreAreaEntidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdInspeccion {
            get {
                return this.idInspeccionField;
            }
            set {
                this.idInspeccionField = value;
                this.RaisePropertyChanged("IdInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdInspeccionPadre {
            get {
                return this.idInspeccionPadreField;
            }
            set {
                this.idInspeccionPadreField = value;
                this.RaisePropertyChanged("IdInspeccionPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NroProyecto {
            get {
                return this.nroProyectoField;
            }
            set {
                this.nroProyectoField = value;
                this.RaisePropertyChanged("NroProyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NroReporte {
            get {
                return this.nroReporteField;
            }
            set {
                this.nroReporteField = value;
                this.RaisePropertyChanged("NroReporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdProyecto {
            get {
                return this.idProyectoField;
            }
            set {
                this.idProyectoField = value;
                this.RaisePropertyChanged("IdProyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NombreProyecto {
            get {
                return this.nombreProyectoField;
            }
            set {
                this.nombreProyectoField = value;
                this.RaisePropertyChanged("NombreProyecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IdCLiente {
            get {
                return this.idCLienteField;
            }
            set {
                this.idCLienteField = value;
                this.RaisePropertyChanged("IdCLiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ClienteRazonSocial {
            get {
                return this.clienteRazonSocialField;
            }
            set {
                this.clienteRazonSocialField = value;
                this.RaisePropertyChanged("ClienteRazonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime FechaInspeccion {
            get {
                return this.fechaInspeccionField;
            }
            set {
                this.fechaInspeccionField = value;
                this.RaisePropertyChanged("FechaInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int IdTipoInspeccion {
            get {
                return this.idTipoInspeccionField;
            }
            set {
                this.idTipoInspeccionField = value;
                this.RaisePropertyChanged("IdTipoInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int IdTipoProceso {
            get {
                return this.idTipoProcesoField;
            }
            set {
                this.idTipoProcesoField = value;
                this.RaisePropertyChanged("IdTipoProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NombreTipoProceso {
            get {
                return this.nombreTipoProcesoField;
            }
            set {
                this.nombreTipoProcesoField = value;
                this.RaisePropertyChanged("NombreTipoProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int IdTipoSistema {
            get {
                return this.idTipoSistemaField;
            }
            set {
                this.idTipoSistemaField = value;
                this.RaisePropertyChanged("IdTipoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int IdTipoClasificacion {
            get {
                return this.idTipoClasificacionField;
            }
            set {
                this.idTipoClasificacionField = value;
                this.RaisePropertyChanged("IdTipoClasificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Recomendacion {
            get {
                return this.recomendacionField;
            }
            set {
                this.recomendacionField = value;
                this.RaisePropertyChanged("Recomendacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string LineadeNegocio {
            get {
                return this.lineadeNegocioField;
            }
            set {
                this.lineadeNegocioField = value;
                this.RaisePropertyChanged("LineadeNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int IdNormaClausula {
            get {
                return this.idNormaClausulaField;
            }
            set {
                this.idNormaClausulaField = value;
                this.RaisePropertyChanged("IdNormaClausula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int IdOrigen {
            get {
                return this.idOrigenField;
            }
            set {
                this.idOrigenField = value;
                this.RaisePropertyChanged("IdOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int IdEntidad {
            get {
                return this.idEntidadField;
            }
            set {
                this.idEntidadField = value;
                this.RaisePropertyChanged("IdEntidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string NombreAreaEntidad {
            get {
                return this.nombreAreaEntidadField;
            }
            set {
                this.nombreAreaEntidadField = value;
                this.RaisePropertyChanged("NombreAreaEntidad");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponsableAreaDetalleBE : BaseBE {
        
        private string idDetalleResponsableAreaField;
        
        private string idInspeccionField;
        
        private int idPersonalField;
        
        private System.DateTime fechaRptaField;
        
        private System.DateTime fechaEnvioField;
        
        private System.DateTime fechaLecturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdDetalleResponsableArea {
            get {
                return this.idDetalleResponsableAreaField;
            }
            set {
                this.idDetalleResponsableAreaField = value;
                this.RaisePropertyChanged("IdDetalleResponsableArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdInspeccion {
            get {
                return this.idInspeccionField;
            }
            set {
                this.idInspeccionField = value;
                this.RaisePropertyChanged("IdInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdPersonal {
            get {
                return this.idPersonalField;
            }
            set {
                this.idPersonalField = value;
                this.RaisePropertyChanged("IdPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime FechaRpta {
            get {
                return this.fechaRptaField;
            }
            set {
                this.fechaRptaField = value;
                this.RaisePropertyChanged("FechaRpta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime FechaEnvio {
            get {
                return this.fechaEnvioField;
            }
            set {
                this.fechaEnvioField = value;
                this.RaisePropertyChanged("FechaEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime FechaLectura {
            get {
                return this.fechaLecturaField;
            }
            set {
                this.fechaLecturaField = value;
                this.RaisePropertyChanged("FechaLectura");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioFirmanteBE : BaseBE {
        
        private string idInspeccionField;
        
        private int idPersonaFirmanteField;
        
        private int idTipoFirmanteField;
        
        private string recomendacionesField;
        
        private string firmaField;
        
        private int upDateEmailField;
        
        private int idTipoPlazoField;
        
        private int tiempoPlazoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdInspeccion {
            get {
                return this.idInspeccionField;
            }
            set {
                this.idInspeccionField = value;
                this.RaisePropertyChanged("IdInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdPersonaFirmante {
            get {
                return this.idPersonaFirmanteField;
            }
            set {
                this.idPersonaFirmanteField = value;
                this.RaisePropertyChanged("IdPersonaFirmante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdTipoFirmante {
            get {
                return this.idTipoFirmanteField;
            }
            set {
                this.idTipoFirmanteField = value;
                this.RaisePropertyChanged("IdTipoFirmante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Recomendaciones {
            get {
                return this.recomendacionesField;
            }
            set {
                this.recomendacionesField = value;
                this.RaisePropertyChanged("Recomendaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
                this.RaisePropertyChanged("Firma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UpDateEmail {
            get {
                return this.upDateEmailField;
            }
            set {
                this.upDateEmailField = value;
                this.RaisePropertyChanged("UpDateEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IdTipoPlazo {
            get {
                return this.idTipoPlazoField;
            }
            set {
                this.idTipoPlazoField = value;
                this.RaisePropertyChanged("IdTipoPlazo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TiempoPlazo {
            get {
                return this.tiempoPlazoField;
            }
            set {
                this.tiempoPlazoField = value;
                this.RaisePropertyChanged("TiempoPlazo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InspeccionAnexoBE : BaseBE {
        
        private string idAnexoField;
        
        private string idInspeccionField;
        
        private string archivoField;
        
        private int ordenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdAnexo {
            get {
                return this.idAnexoField;
            }
            set {
                this.idAnexoField = value;
                this.RaisePropertyChanged("IdAnexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdInspeccion {
            get {
                return this.idInspeccionField;
            }
            set {
                this.idInspeccionField = value;
                this.RaisePropertyChanged("IdInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("Archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProyectoActividadBE : BaseBE {
        
        private string idActProyField;
        
        private int idPryectoField;
        
        private int idActividadField;
        
        private string nombreActividadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdActProy {
            get {
                return this.idActProyField;
            }
            set {
                this.idActProyField = value;
                this.RaisePropertyChanged("IdActProy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdPryecto {
            get {
                return this.idPryectoField;
            }
            set {
                this.idPryectoField = value;
                this.RaisePropertyChanged("IdPryecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("IdActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NombreActividad {
            get {
                return this.nombreActividadField;
            }
            set {
                this.nombreActividadField = value;
                this.RaisePropertyChanged("NombreActividad");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InspectorDetalleBE : BaseBE {
        
        private string idDetalleInspeccionField;
        
        private string idInspectorField;
        
        private string recomendacionesField;
        
        private int idClausulaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdDetalleInspeccion {
            get {
                return this.idDetalleInspeccionField;
            }
            set {
                this.idDetalleInspeccionField = value;
                this.RaisePropertyChanged("IdDetalleInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdInspector {
            get {
                return this.idInspectorField;
            }
            set {
                this.idInspectorField = value;
                this.RaisePropertyChanged("IdInspector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Recomendaciones {
            get {
                return this.recomendacionesField;
            }
            set {
                this.recomendacionesField = value;
                this.RaisePropertyChanged("Recomendaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdClausula {
            get {
                return this.idClausulaField;
            }
            set {
                this.idClausulaField = value;
                this.RaisePropertyChanged("IdClausula");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponsableAreaBE : BaseBE {
        
        private string idInspeccionField;
        
        private string idPersonalField;
        
        private int idTipoPersonalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdInspeccion {
            get {
                return this.idInspeccionField;
            }
            set {
                this.idInspeccionField = value;
                this.RaisePropertyChanged("IdInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdPersonal {
            get {
                return this.idPersonalField;
            }
            set {
                this.idPersonalField = value;
                this.RaisePropertyChanged("IdPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdTipoPersonal {
            get {
                return this.idTipoPersonalField;
            }
            set {
                this.idTipoPersonalField = value;
                this.RaisePropertyChanged("IdTipoPersonal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InspectorBE : BaseBE {
        
        private string idInspectorField;
        
        private string idInspeccionField;
        
        private int idPersonalField;
        
        private int principalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdInspector {
            get {
                return this.idInspectorField;
            }
            set {
                this.idInspectorField = value;
                this.RaisePropertyChanged("IdInspector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdInspeccion {
            get {
                return this.idInspeccionField;
            }
            set {
                this.idInspeccionField = value;
                this.RaisePropertyChanged("IdInspeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdPersonal {
            get {
                return this.idPersonalField;
            }
            set {
                this.idPersonalField = value;
                this.RaisePropertyChanged("IdPersonal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
                this.RaisePropertyChanged("Principal");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ControlInspeccionesSoapChannel : SIMANET_W22R.srvGestionCalidad.ControlInspeccionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlInspeccionesSoapClient : System.ServiceModel.ClientBase<SIMANET_W22R.srvGestionCalidad.ControlInspeccionesSoap>, SIMANET_W22R.srvGestionCalidad.ControlInspeccionesSoap {
        
        public ControlInspeccionesSoapClient() {
        }
        
        public ControlInspeccionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlInspeccionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlInspeccionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlInspeccionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Inspeccion_ListarInspectores(string Id1, string UserName) {
            return base.Channel.Inspeccion_ListarInspectores(Id1, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Inspeccion_ListarInspectoresAsync(string Id1, string UserName) {
            return base.Channel.Inspeccion_ListarInspectoresAsync(Id1, UserName);
        }
        
        public System.Data.DataTable ListarResponsablesPorArea(string Id1, string UserName) {
            return base.Channel.ListarResponsablesPorArea(Id1, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarResponsablesPorAreaAsync(string Id1, string UserName) {
            return base.Channel.ListarResponsablesPorAreaAsync(Id1, UserName);
        }
        
        public string Inspeccion_ModificarInsertarInspector(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE) {
            return base.Channel.Inspeccion_ModificarInsertarInspector(oBaseBE);
        }
        
        public System.Threading.Tasks.Task<string> Inspeccion_ModificarInsertarInspectorAsync(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE) {
            return base.Channel.Inspeccion_ModificarInsertarInspectorAsync(oBaseBE);
        }
        
        public SIMANET_W22R.srvGestionCalidad.InspectorBE DetalleInspector(string IdInspector) {
            return base.Channel.DetalleInspector(IdInspector);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.InspectorBE> DetalleInspectorAsync(string IdInspector) {
            return base.Channel.DetalleInspectorAsync(IdInspector);
        }
        
        public string Inspeccion_ModficarInsertarResponsable(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE) {
            return base.Channel.Inspeccion_ModficarInsertarResponsable(oBaseBE);
        }
        
        public System.Threading.Tasks.Task<string> Inspeccion_ModficarInsertarResponsableAsync(SIMANET_W22R.srvGestionCalidad.BaseBE oBaseBE) {
            return base.Channel.Inspeccion_ModficarInsertarResponsableAsync(oBaseBE);
        }
        
        public SIMANET_W22R.srvGestionCalidad.ResponsableAreaBE Inspeccion_DetalleResponsableArea(string IdPersonal) {
            return base.Channel.Inspeccion_DetalleResponsableArea(IdPersonal);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.ResponsableAreaBE> Inspeccion_DetalleResponsableAreaAsync(string IdPersonal) {
            return base.Channel.Inspeccion_DetalleResponsableAreaAsync(IdPersonal);
        }
        
        public System.Data.DataTable ListarInspeccionesxInspector(string IdInspector, string UserName) {
            return base.Channel.ListarInspeccionesxInspector(IdInspector, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarInspeccionesxInspectorAsync(string IdInspector, string UserName) {
            return base.Channel.ListarInspeccionesxInspectorAsync(IdInspector, UserName);
        }
        
        public string InsertaModificaDetalledeInspeccion(SIMANET_W22R.srvGestionCalidad.InspectorDetalleBE oInspectorDetalleBE) {
            return base.Channel.InsertaModificaDetalledeInspeccion(oInspectorDetalleBE);
        }
        
        public System.Threading.Tasks.Task<string> InsertaModificaDetalledeInspeccionAsync(SIMANET_W22R.srvGestionCalidad.InspectorDetalleBE oInspectorDetalleBE) {
            return base.Channel.InsertaModificaDetalledeInspeccionAsync(oInspectorDetalleBE);
        }
        
        public System.Data.DataTable ListarProyectosActividadSIMA(string IdProyecto, string UserName) {
            return base.Channel.ListarProyectosActividadSIMA(IdProyecto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarProyectosActividadSIMAAsync(string IdProyecto, string UserName) {
            return base.Channel.ListarProyectosActividadSIMAAsync(IdProyecto, UserName);
        }
        
        public System.Data.DataTable BuscarActividad(string NombreActividad, string UserName) {
            return base.Channel.BuscarActividad(NombreActividad, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarActividadAsync(string NombreActividad, string UserName) {
            return base.Channel.BuscarActividadAsync(NombreActividad, UserName);
        }
        
        public System.Data.DataTable BuscarAreaEntidad(string NombreAreaEntidad, int IdUsuario, string UserName) {
            return base.Channel.BuscarAreaEntidad(NombreAreaEntidad, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarAreaEntidadAsync(string NombreAreaEntidad, int IdUsuario, string UserName) {
            return base.Channel.BuscarAreaEntidadAsync(NombreAreaEntidad, IdUsuario, UserName);
        }
        
        public System.Data.DataTable BuscarAreaEntidad_Inspeccion(string NombreAreaEntidad, string UserName) {
            return base.Channel.BuscarAreaEntidad_Inspeccion(NombreAreaEntidad, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarAreaEntidad_InspeccionAsync(string NombreAreaEntidad, string UserName) {
            return base.Channel.BuscarAreaEntidad_InspeccionAsync(NombreAreaEntidad, UserName);
        }
        
        public string ModficarInsertarProyectoActividadSIMA(SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE oProyectoActividadBE) {
            return base.Channel.ModficarInsertarProyectoActividadSIMA(oProyectoActividadBE);
        }
        
        public System.Threading.Tasks.Task<string> ModficarInsertarProyectoActividadSIMAAsync(SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE oProyectoActividadBE) {
            return base.Channel.ModficarInsertarProyectoActividadSIMAAsync(oProyectoActividadBE);
        }
        
        public SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE DetalleActivadProyecto(string IdProyecto, string IdActividad) {
            return base.Channel.DetalleActivadProyecto(IdProyecto, IdActividad);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.ProyectoActividadBE> DetalleActivadProyectoAsync(string IdProyecto, string IdActividad) {
            return base.Channel.DetalleActivadProyectoAsync(IdProyecto, IdActividad);
        }
        
        public string AdministrarInspeccionAnexos(SIMANET_W22R.srvGestionCalidad.InspeccionAnexoBE oInspeccionAnexoBE) {
            return base.Channel.AdministrarInspeccionAnexos(oInspeccionAnexoBE);
        }
        
        public System.Threading.Tasks.Task<string> AdministrarInspeccionAnexosAsync(SIMANET_W22R.srvGestionCalidad.InspeccionAnexoBE oInspeccionAnexoBE) {
            return base.Channel.AdministrarInspeccionAnexosAsync(oInspeccionAnexoBE);
        }
        
        public System.Data.DataTable ListarInspeccionAnexos(string IdInspeccion, string UserName) {
            return base.Channel.ListarInspeccionAnexos(IdInspeccion, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarInspeccionAnexosAsync(string IdInspeccion, string UserName) {
            return base.Channel.ListarInspeccionAnexosAsync(IdInspeccion, UserName);
        }
        
        public System.Data.DataTable ListarUsuariosFirmantes(string IdInspeccion, string IdUsuarioFirmante, string UserName) {
            return base.Channel.ListarUsuariosFirmantes(IdInspeccion, IdUsuarioFirmante, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosFirmantesAsync(string IdInspeccion, string IdUsuarioFirmante, string UserName) {
            return base.Channel.ListarUsuariosFirmantesAsync(IdInspeccion, IdUsuarioFirmante, UserName);
        }
        
        public System.Data.DataTable ListarUsuariosFirmantesRefCruz(string IdInspeccion, string UserName) {
            return base.Channel.ListarUsuariosFirmantesRefCruz(IdInspeccion, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarUsuariosFirmantesRefCruzAsync(string IdInspeccion, string UserName) {
            return base.Channel.ListarUsuariosFirmantesRefCruzAsync(IdInspeccion, UserName);
        }
        
        public string ModificaInsertaUsuariosFirmantes(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.ModificaInsertaUsuariosFirmantes(oUsuarioFirmanteBE);
        }
        
        public System.Threading.Tasks.Task<string> ModificaInsertaUsuariosFirmantesAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.ModificaInsertaUsuariosFirmantesAsync(oUsuarioFirmanteBE);
        }
        
        public string InsModPersonalFirmantePorTipo(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.InsModPersonalFirmantePorTipo(oUsuarioFirmanteBE);
        }
        
        public System.Threading.Tasks.Task<string> InsModPersonalFirmantePorTipoAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.InsModPersonalFirmantePorTipoAsync(oUsuarioFirmanteBE);
        }
        
        public string ModificaInsertaFirmas(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.ModificaInsertaFirmas(oUsuarioFirmanteBE);
        }
        
        public System.Threading.Tasks.Task<string> ModificaInsertaFirmasAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.ModificaInsertaFirmasAsync(oUsuarioFirmanteBE);
        }
        
        public int EliminaUsuariosFirmantes(string IdInspeccion, string IdUsuarioFirmante, int IdEsatdo, int IdUsuario, string UserName) {
            return base.Channel.EliminaUsuariosFirmantes(IdInspeccion, IdUsuarioFirmante, IdEsatdo, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<int> EliminaUsuariosFirmantesAsync(string IdInspeccion, string IdUsuarioFirmante, int IdEsatdo, int IdUsuario, string UserName) {
            return base.Channel.EliminaUsuariosFirmantesAsync(IdInspeccion, IdUsuarioFirmante, IdEsatdo, IdUsuario, UserName);
        }
        
        public int ActualizaNroMsgRecibidos(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.ActualizaNroMsgRecibidos(oUsuarioFirmanteBE);
        }
        
        public System.Threading.Tasks.Task<int> ActualizaNroMsgRecibidosAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.ActualizaNroMsgRecibidosAsync(oUsuarioFirmanteBE);
        }
        
        public int FirmaAprobarFromEMail(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.FirmaAprobarFromEMail(oUsuarioFirmanteBE);
        }
        
        public System.Threading.Tasks.Task<int> FirmaAprobarFromEMailAsync(SIMANET_W22R.srvGestionCalidad.UsuarioFirmanteBE oUsuarioFirmanteBE) {
            return base.Channel.FirmaAprobarFromEMailAsync(oUsuarioFirmanteBE);
        }
        
        public int InspeccionCambiarEstado(string IdInspeccion, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.InspeccionCambiarEstado(IdInspeccion, IdEstado, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<int> InspeccionCambiarEstadoAsync(string IdInspeccion, int IdEstado, int IdUsuario, string UserName) {
            return base.Channel.InspeccionCambiarEstadoAsync(IdInspeccion, IdEstado, IdUsuario, UserName);
        }
        
        public System.Data.DataTable BuscarProyectodeInspeccion(string NombreProyecto, string UserName) {
            return base.Channel.BuscarProyectodeInspeccion(NombreProyecto, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarProyectodeInspeccionAsync(string NombreProyecto, string UserName) {
            return base.Channel.BuscarProyectodeInspeccionAsync(NombreProyecto, UserName);
        }
        
        public System.Data.DataTable ListarDetallePorReponsabledeArea(string IdInspeccion, int IdPersonal, string UserName) {
            return base.Channel.ListarDetallePorReponsabledeArea(IdInspeccion, IdPersonal, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarDetallePorReponsabledeAreaAsync(string IdInspeccion, int IdPersonal, string UserName) {
            return base.Channel.ListarDetallePorReponsabledeAreaAsync(IdInspeccion, IdPersonal, UserName);
        }
        
        public SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE DetallePorReponsabledeAreaRpt(string IdDetalleResponsableArea, string UserName) {
            return base.Channel.DetallePorReponsabledeAreaRpt(IdDetalleResponsableArea, UserName);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE> DetallePorReponsabledeAreaRptAsync(string IdDetalleResponsableArea, string UserName) {
            return base.Channel.DetallePorReponsabledeAreaRptAsync(IdDetalleResponsableArea, UserName);
        }
        
        public int DetallePorReponsabledeAreaCambiarEstado(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE) {
            return base.Channel.DetallePorReponsabledeAreaCambiarEstado(oResponsableAreaDetalleBE);
        }
        
        public System.Threading.Tasks.Task<int> DetallePorReponsabledeAreaCambiarEstadoAsync(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE) {
            return base.Channel.DetallePorReponsabledeAreaCambiarEstadoAsync(oResponsableAreaDetalleBE);
        }
        
        public int ResponsabledeAreaDetalle_InsertaModifica(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE) {
            return base.Channel.ResponsabledeAreaDetalle_InsertaModifica(oResponsableAreaDetalleBE);
        }
        
        public System.Threading.Tasks.Task<int> ResponsabledeAreaDetalle_InsertaModificaAsync(SIMANET_W22R.srvGestionCalidad.ResponsableAreaDetalleBE oResponsableAreaDetalleBE) {
            return base.Channel.ResponsabledeAreaDetalle_InsertaModificaAsync(oResponsableAreaDetalleBE);
        }
        
        public System.Data.DataTable ResumenInspeccionesPorEstado(int Año, int IdUsuario, string UserName) {
            return base.Channel.ResumenInspeccionesPorEstado(Año, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenInspeccionesPorEstadoAsync(int Año, int IdUsuario, string UserName) {
            return base.Channel.ResumenInspeccionesPorEstadoAsync(Año, IdUsuario, UserName);
        }
        
        public System.Data.DataTable ResumenNoConformeTipoEntidad(int Año, int IdUsuario, string UserName) {
            return base.Channel.ResumenNoConformeTipoEntidad(Año, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeTipoEntidadAsync(int Año, int IdUsuario, string UserName) {
            return base.Channel.ResumenNoConformeTipoEntidadAsync(Año, IdUsuario, UserName);
        }
        
        public System.Data.DataTable BuscarAprobador(string ApellidosyNombres, string UserName) {
            return base.Channel.BuscarAprobador(ApellidosyNombres, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarAprobadorAsync(string ApellidosyNombres, string UserName) {
            return base.Channel.BuscarAprobadorAsync(ApellidosyNombres, UserName);
        }
        
        public int BloqueaRegistroInspeccion(string IdInspeccion, int Block, string UserName) {
            return base.Channel.BloqueaRegistroInspeccion(IdInspeccion, Block, UserName);
        }
        
        public System.Threading.Tasks.Task<int> BloqueaRegistroInspeccionAsync(string IdInspeccion, int Block, string UserName) {
            return base.Channel.BloqueaRegistroInspeccionAsync(IdInspeccion, Block, UserName);
        }
        
        public System.Data.DataTable Inspeccion_Listar(string Id1, int IdUsuario, string UserName) {
            return base.Channel.Inspeccion_Listar(Id1, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Inspeccion_ListarAsync(string Id1, int IdUsuario, string UserName) {
            return base.Channel.Inspeccion_ListarAsync(Id1, IdUsuario, UserName);
        }
        
        public SIMANET_W22R.srvGestionCalidad.InspeccionBE Inspeccion_Detalle(string Id1, int IdUsuario, string UserName) {
            return base.Channel.Inspeccion_Detalle(Id1, IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<SIMANET_W22R.srvGestionCalidad.InspeccionBE> Inspeccion_DetalleAsync(string Id1, int IdUsuario, string UserName) {
            return base.Channel.Inspeccion_DetalleAsync(Id1, IdUsuario, UserName);
        }
        
        public System.Data.DataTable Inspeccion_ListarPorResponsableArea(string IdPersonal, string UserName) {
            return base.Channel.Inspeccion_ListarPorResponsableArea(IdPersonal, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Inspeccion_ListarPorResponsableAreaAsync(string IdPersonal, string UserName) {
            return base.Channel.Inspeccion_ListarPorResponsableAreaAsync(IdPersonal, UserName);
        }
        
        public string Inspeccion_Insertar(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE) {
            return base.Channel.Inspeccion_Insertar(oInspeccionBE);
        }
        
        public System.Threading.Tasks.Task<string> Inspeccion_InsertarAsync(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE) {
            return base.Channel.Inspeccion_InsertarAsync(oInspeccionBE);
        }
        
        public int Inspeccion_Modificar(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE) {
            return base.Channel.Inspeccion_Modificar(oInspeccionBE);
        }
        
        public System.Threading.Tasks.Task<int> Inspeccion_ModificarAsync(SIMANET_W22R.srvGestionCalidad.InspeccionBE oInspeccionBE) {
            return base.Channel.Inspeccion_ModificarAsync(oInspeccionBE);
        }
        
        public System.Data.DataTable ResumenNoConformeIP_SIMA(int Año, int MesHasta, int IdOrigen, string UserName) {
            return base.Channel.ResumenNoConformeIP_SIMA(Año, MesHasta, IdOrigen, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeIP_SIMAAsync(int Año, int MesHasta, int IdOrigen, string UserName) {
            return base.Channel.ResumenNoConformeIP_SIMAAsync(Año, MesHasta, IdOrigen, UserName);
        }
        
        public System.Data.DataTable ResumenNoConformeIP(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformeIP(Año, MesHasta, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeIPAsync(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformeIPAsync(Año, MesHasta, UserName);
        }
        
        public System.Data.DataTable ResumenNoConformeSIMA(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformeSIMA(Año, MesHasta, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformeSIMAAsync(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformeSIMAAsync(Año, MesHasta, UserName);
        }
        
        public System.Data.DataTable ResumenNoConformePorProyecto_Mensual(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformePorProyecto_Mensual(Año, MesHasta, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformePorProyecto_MensualAsync(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformePorProyecto_MensualAsync(Año, MesHasta, UserName);
        }
        
        public System.Data.DataTable ResumenNoConformePorIP_SIMA_Mensual(int Año, int MesHasta, int IdOrigen, string UserName) {
            return base.Channel.ResumenNoConformePorIP_SIMA_Mensual(Año, MesHasta, IdOrigen, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformePorIP_SIMA_MensualAsync(int Año, int MesHasta, int IdOrigen, string UserName) {
            return base.Channel.ResumenNoConformePorIP_SIMA_MensualAsync(Año, MesHasta, IdOrigen, UserName);
        }
        
        public System.Data.DataTable ResumenNoConformePorTipodeInspeccion(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformePorTipodeInspeccion(Año, MesHasta, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ResumenNoConformePorTipodeInspeccionAsync(int Año, int MesHasta, string UserName) {
            return base.Channel.ResumenNoConformePorTipodeInspeccionAsync(Año, MesHasta, UserName);
        }
        
        public System.Data.DataTable ListarSolicitudAprobacion(int IdUsuario, string UserName) {
            return base.Channel.ListarSolicitudAprobacion(IdUsuario, UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarSolicitudAprobacionAsync(int IdUsuario, string UserName) {
            return base.Channel.ListarSolicitudAprobacionAsync(IdUsuario, UserName);
        }
    }
}
